'use client';
import {useMemo,useState} from 'react';

type Alumni={name:string;cohort:string;year:string;position:string;bio:string;published:boolean;certificate:string;honours:string};
const alumni:Alumni[]=[
 {name:'Abdullah Hassan',cohort:'Cohort 2026',year:'2026',position:'Completed from An-Nas to Al-Baqarah',bio:'A dedicated graduate who completed the two-year Quran memorization programme with strong commitment to revision and tajweed.',published:true,certificate:'ALH-2026-ST1001',honours:'Excellent final memorization and strong tajweed.'},
 {name:'Maryam Ahmed',cohort:'Cohort 2026',year:'2026',position:'Completed from Al-Baqarah to An-Nas',bio:'A committed graduate whose final term reflected excellent memorization, fluency and tajweed.',published:true,certificate:'ALH-2026-ST1003',honours:'Outstanding fluency and consistent revision.'},
 {name:'Yusuf Ramadhan',cohort:'Cohort 2025',year:'2025',position:'Completed the two-year programme',bio:'Graduate profile maintained privately by the school.',published:false,certificate:'ALH-2025-ST1007',honours:'',},
];
export default function Alumni(){
 const [cohort,setCohort]=useState('All'); const [selected,setSelected]=useState<Alumni|null>(null); const [certificate,setCertificate]=useState<Alumni|null>(null);
 const rows=useMemo(()=>alumni.filter(a=>a.published&&(cohort==='All'||a.cohort===cohort)),[cohort]);
 return <main className="mx-auto max-w-7xl px-5 py-8">
  <div className="rounded-3xl bg-gradient-to-br from-emerald-950 via-emerald-900 to-[#b78325] p-7 text-white md:p-10"><div className="max-w-3xl"><div className="text-xs font-bold uppercase tracking-[.25em] text-amber-200">Graduates & legacy</div><h1 className="mt-3 text-4xl font-black md:text-5xl">Honouring Our Huffaz</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-emerald-50 md:text-base">Every graduate can keep a permanent school record after completing the two-year programme. Only profiles approved for public publication appear here.</p></div></div>
  <div className="mt-7 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-black">Alumni by cohort</h2><p className="text-sm text-slate-500">Public profiles are controlled from the school CMS.</p></div><select className="input max-w-xs" value={cohort} onChange={e=>setCohort(e.target.value)}><option>All</option><option>Cohort 2026</option><option>Cohort 2025</option></select></div>
  <section className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{rows.map(a=><article className="card overflow-hidden" key={a.name}><div className="flex h-36 items-end bg-gradient-to-br from-emerald-950 via-emerald-800 to-amber-700 p-5"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-white/20 text-xl font-black text-white ring-2 ring-white/60">{a.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div></div><div className="p-5"><div className="flex items-center justify-between"><span className="pill bg-emerald-50 text-emerald-700">{a.cohort}</span><span className="text-xs text-slate-500">Graduate</span></div><h2 className="mt-3 text-xl font-black">{a.name}</h2><p className="mt-2 text-sm font-semibold text-emerald-800">{a.position}</p><p className="mt-3 text-sm leading-6 text-slate-600">{a.bio}</p><div className="mt-5 flex flex-wrap gap-2"><button className="btn btn-primary" onClick={()=>setSelected(a)}>Read full profile</button><button className="btn bg-amber-50 text-amber-800" onClick={()=>setCertificate(a)}>Certificate</button></div></div></article>)}</section>
  <section className="mt-10 card p-6"><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><div className="text-xs font-bold uppercase tracking-widest text-amber-700">Permanent academic legacy</div><h2 className="mt-1 text-2xl font-black">Graduation is a transition, not a deletion.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-600">After Year 2 Term 3, the school can preserve the student's approved evaluations, Quran journey, report cards, attendance history and certificate in the alumni record. Private academic information remains protected; the public website only displays what the administrator chooses to publish.</p></div><div className="rounded-2xl bg-emerald-950 p-6 text-white"><div className="text-sm font-bold text-amber-300">Certificate rule</div><div className="mt-2 text-lg font-black">Final evaluation approved + all three Term 3 evaluations approved</div><div className="mt-2 text-sm text-emerald-100">→ Graduate status → Certificate → Alumni profile</div></div></div></section>
  {selected&&<Modal title={selected.name} close={()=>setSelected(null)}><div className="grid gap-5 md:grid-cols-[140px_1fr]"><div className="flex h-36 w-36 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-950 to-amber-600 text-3xl font-black text-white">{selected.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><div className="pill inline-block bg-emerald-50 text-emerald-700">{selected.cohort}</div><h3 className="mt-3 text-xl font-black">Quran Memorization Graduate</h3><p className="mt-2 text-sm leading-7 text-slate-600">{selected.bio}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Info label="Final pathway" value={selected.position}/><Info label="Certificate" value={selected.certificate}/><Info label="Graduation year" value={selected.year}/><Info label="Honour" value={selected.honours||'—'}/></div></div></div></Modal>}
  {certificate&&<Modal title="Certificate of Completion" close={()=>setCertificate(null)}><div id="certificate" className="mx-auto max-w-2xl border-[10px] border-double border-amber-500 bg-[#fffdf5] p-8 text-center shadow-sm md:p-12"><div className="text-xs font-black tracking-[.28em] text-emerald-900">ALIYU AND MAIMUNA CENTER FOR QUR'ANIC MEMORIZATION</div><div className="mt-6 text-4xl font-serif font-black text-emerald-950">Certificate of Completion</div><div className="my-5 text-sm text-slate-600">This certifies that</div><div className="text-3xl font-black text-slate-900">{certificate.name}</div><div className="mx-auto mt-4 max-w-xl text-sm leading-7 text-slate-700">has successfully completed the Two-Year Quran Memorization Programme and is honoured as a graduate of the {certificate.cohort} cohort.</div><div className="mt-7 grid gap-3 text-xs text-slate-600 sm:grid-cols-3"><div><b className="block text-slate-900">Programme</b>Two Years</div><div><b className="block text-slate-900">Final Term</b>Term 3</div><div><b className="block text-slate-900">Certificate No.</b>{certificate.certificate}</div></div><div className="mt-10 flex justify-between border-t pt-5 text-xs"><span>Principal</span><span>Director</span></div></div><button className="btn btn-primary mt-5 w-full" onClick={()=>window.print()}>Print certificate</button></Modal>}
 </main>
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-[11px] text-slate-500">{label}</div><b className="text-sm">{value}</b></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-2xl bg-white p-5 md:p-7"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-black">{title}</h2><button onClick={close} className="rounded-full bg-slate-100 px-3 py-2 font-bold">✕</button></div><div className="mt-5">{children}</div></div></div>}
