'use client';
import AdminShell from '@/components/AdminShell';
import { createProgram, createProgramStructure, createProgramTerm, createProgramYear, loadProgramSetup, updateProgram } from '@/lib/admin-management-store';
import { useEffect, useState } from 'react';

export default function ProgramsAdmin(){
 const [data,setData]=useState<any>({programs:[],structures:[],years:[],terms:[]}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const [program,setProgram]=useState({name:'',description:''}); const [structure,setStructure]=useState({programId:'',versionName:'2026/27',effectiveFrom:'2026-09-01'}); const [year,setYear]=useState({structureId:'',yearNumber:1,name:'Year 1'}); const [term,setTerm]=useState({yearDefinitionId:'',termNumber:1,name:'Term 1',startsMonth:1,endsMonth:4});
 async function refresh(){setData(await loadProgramSetup())} useEffect(()=>{refresh()},[]);
 async function act(fn:()=>Promise<any>,ok:string){setBusy(true);setMessage('');try{await fn();setMessage(ok);await refresh()}catch(e:any){setMessage(e?.message||'Operation failed')}finally{setBusy(false)}}
 return <AdminShell title="Program & Academic Setup"><div className="space-y-6">
  {message&&<div className="rounded-xl border bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</div>}
  <div className="grid gap-4 lg:grid-cols-3">
   <div className="card p-5"><h2 className="font-black">Programmes</h2><p className="mt-1 text-xs text-slate-500">Create and activate the school programmes.</p><div className="mt-4 space-y-2"><input className="input" placeholder="Programme name" value={program.name} onChange={e=>setProgram({...program,name:e.target.value})}/><textarea className="input" placeholder="Description" value={program.description} onChange={e=>setProgram({...program,description:e.target.value})}/><button className="btn btn-primary w-full" disabled={busy||!program.name} onClick={()=>act(async()=>{await createProgram(program);setProgram({name:'',description:''})},'Programme created')}>Create programme</button></div><div className="mt-5 space-y-2">{data.programs.map((p:any)=><div key={p.id} className="rounded-xl border p-3"><div className="font-bold">{p.name}</div><div className="text-xs text-slate-500">{p.description||'No description'}</div><button className="btn mt-2 bg-slate-100" onClick={()=>act(()=>updateProgram(p.id,{active:!p.active}),p.active?'Programme deactivated':'Programme activated')}>{p.active?'Deactivate':'Activate'}</button></div>)}</div></div>
   <div className="card p-5"><h2 className="font-black">Academic structure</h2><p className="mt-1 text-xs text-slate-500">Define the current academic structure and graduation rules.</p><div className="mt-4 space-y-2"><select className="input" value={structure.programId} onChange={e=>setStructure({...structure,programId:e.target.value})}><option value="">Select programme</option>{data.programs.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="input" placeholder="Version name" value={structure.versionName} onChange={e=>setStructure({...structure,versionName:e.target.value})}/><input className="input" type="date" value={structure.effectiveFrom} onChange={e=>setStructure({...structure,effectiveFrom:e.target.value})}/><button className="btn btn-primary w-full" disabled={busy||!structure.programId} onClick={()=>act(()=>createProgramStructure(structure),'Structure version created')}>Create current structure</button></div><div className="mt-5 space-y-2">{data.structures.map((s:any)=><div className="rounded-xl border p-3" key={s.id}><b>{s.version_name}</b><div className="text-xs text-slate-500">{s.effective_from} · {s.is_current?'Current':'Archived'} · Quran completion: {s.graduation_requires_quran_completion?'Required':'Not required'}</div></div>)}</div></div>
   <div className="card p-5"><h2 className="font-black">Years & terms</h2><p className="mt-1 text-xs text-slate-500">Set Year 1/2 and the term/evaluation structure.</p><div className="mt-4 space-y-2"><select className="input" value={year.structureId} onChange={e=>setYear({...year,structureId:e.target.value})}><option value="">Select structure</option>{data.structures.map((s:any)=><option key={s.id} value={s.id}>{s.version_name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input className="input" type="number" min="1" max="2" value={year.yearNumber} onChange={e=>setYear({...year,yearNumber:Number(e.target.value)})}/><input className="input" placeholder="Year name" value={year.name} onChange={e=>setYear({...year,name:e.target.value})}/></div><button className="btn btn-primary w-full" disabled={busy||!year.structureId} onClick={()=>act(()=>createProgramYear(year),'Year definition created')}>Add year</button><select className="input" value={term.yearDefinitionId} onChange={e=>setTerm({...term,yearDefinitionId:e.target.value})}><option value="">Select year</option>{data.years.map((y:any)=><option key={y.id} value={y.id}>{y.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input className="input" type="number" min="1" max="3" value={term.termNumber} onChange={e=>setTerm({...term,termNumber:Number(e.target.value)})}/><input className="input" placeholder="Term name" value={term.name} onChange={e=>setTerm({...term,name:e.target.value})}/></div><div className="grid grid-cols-2 gap-2"><input className="input" type="number" min="1" max="12" placeholder="Start month" value={term.startsMonth} onChange={e=>setTerm({...term,startsMonth:Number(e.target.value)})}/><input className="input" type="number" min="1" max="12" placeholder="End month" value={term.endsMonth} onChange={e=>setTerm({...term,endsMonth:Number(e.target.value)})}/></div><button className="btn btn-primary w-full" disabled={busy||!term.yearDefinitionId} onClick={()=>act(()=>createProgramTerm(term),'Term definition created')}>Add term</button></div><div className="mt-5 space-y-2">{data.terms.map((t:any)=><div className="rounded-xl border p-3" key={t.id}><b>{t.name}</b><div className="text-xs text-slate-500">{t.starts_month||'—'}–{t.ends_month||'—'} · {t.evaluation_count} evaluations</div></div>)}</div></div>
  </div>
 </div></AdminShell>
}
