import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';

export async function GET(req: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
  const role = profile?.role || '';
  if (!['security', 'admin', 'super_admin', 'principal'].includes(role)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  const q = req.nextUrl.searchParams.get('q')?.trim();
  if (!q) return NextResponse.json({ error: 'q required' }, { status: 400 });

  const admin = createAdminClient();

  // QR payloads generated by AMQM IDs contain the canonical UUID.
  try {
    const parsed = JSON.parse(q);
    if (parsed?.institution === 'AMQM' && parsed?.id) {
      const rawType = String(parsed.type || '').toUpperCase();
      const isStaff = rawType === 'STAFF' || rawType === 'MANAGEMENT';
      if (isStaff) {
        const { data } = await admin.from('profiles')
          .select('id,full_name,role,avatar_url,staff_id')
          .eq('id', String(parsed.id)).maybeSingle();
        if (data) return NextResponse.json({
          type:'staff', id:data.id, name:data.full_name, role:data.role, photoUrl:data.avatar_url
        });
      } else {
        const { data } = await admin.from('students')
          .select('id,full_name,admission_no,section,photo_url,classes:class_id(name)')
          .eq('id', String(parsed.id)).maybeSingle();
        if (data) return NextResponse.json({
          type:'student', id:data.id, name:data.full_name,
          admissionNo:data.admission_no, section:data.section,
          photoUrl:data.photo_url, className:(data.classes as any)?.name || null
        });
      }
      return NextResponse.json({ error:'not_found' }, { status:404 });
    }
  } catch {
    // Not JSON: continue as a printed ID/barcode.
  }

  // Printed IDs are matched exactly against their canonical school ID fields.
  const [admissionRes, studentNumberRes, staffRes] = await Promise.all([
    admin.from('students')
      .select('id,full_name,admission_no,section,photo_url,classes:class_id(name)')
      .eq('admission_no', q).limit(1).maybeSingle(),
    admin.from('students')
      .select('id,full_name,admission_no,section,photo_url,classes:class_id(name)')
      .eq('student_id_number', q).limit(1).maybeSingle(),
    admin.from('profiles')
      .select('id,full_name,role,avatar_url,staff_id')
      .eq('staff_id', q).limit(1).maybeSingle(),
  ]);

  const student = admissionRes.data || studentNumberRes.data;
  if (student) return NextResponse.json({
    type:'student', id:student.id, name:student.full_name,
    admissionNo:student.admission_no, section:student.section,
    photoUrl:student.photo_url, className:(student.classes as any)?.name || null
  });

  if (staffRes.data) return NextResponse.json({
    type:'staff', id:staffRes.data.id, name:staffRes.data.full_name,
    role:staffRes.data.role, photoUrl:staffRes.data.avatar_url
  });

  return NextResponse.json({ error:'not_found' }, { status:404 });
}
