'use client';
import AdminShell from '@/components/AdminShell';
import SectionBadge from '@/components/SectionBadge';
import { loadStudents,loadInvoices,loadCurrentAcademicTerm } from '@/lib/live-store';
import { createFeeStructure,updateFeeStructure,loadFeeStructures,loadFinanceSummary,recordPayment,syncStudentFeeAllocations } from '@/lib/admin-management-store';
import { createClient } from '@/lib/supabase/client';
import { Student } from '@/lib/data';
import { useEffect,useMemo,useState } from 'react';
import {loadCMSSettings,saveCMSSetting} from '@/lib/cms-live-store';

const termLabel=(t:any)=>t?.term_number===1?'First Term':t?.term_number===2?'Second Term':t?.term_number===3?'Third Term':t?.name||'Term';

export default function Fees(){
 const [currency,setCurrency]=useState('NGN'),[schoolSettings,setSchoolSettings]=useState<any>({});
 const [students,setStudents]=useState<Student[]>([]),[invoices,setInvoices]=useState<any[]>([]),[structures,setStructures]=useState<any[]>([]),[summary,setSummary]=useState<any>({fees:[],payments:[]}),[years,setYears]=useState<any[]>([]),[terms,setTerms]=useState<any[]>([]),[selectedTermId,setSelectedTermId]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [fee,setFee]=useState({id:'',academicYearId:'',termId:'',section:'day' as 'day'|'boarding',name:'Term Fee',amount:'',dueDate:''});
 const [payment,setPayment]=useState({studentId:'',amount:'',method:'Cash',reference:'',notes:''});
 const [bank,setBank]=useState({bank_name:'',account_name:'',account_number:'',reference_instruction:''});
 async function loadYears(){const {data}=await createClient().from('academic_years').select('id,name,is_current').order('starts_on',{ascending:false});return data||[]}
 async function loadCurrency(){const {data}=await createClient().from('site_settings').select('value').eq('key','currency').maybeSingle();return data?.value?.symbol||data?.value?.code||'NGN'}
 async function loadTerms(){const {data}=await createClient().from('terms').select('id,name,term_number,academic_year_id,academic_years:academic_year_id(name,is_current)').order('starts_on',{ascending:false}).order('term_number');return data||[]}
 async function refresh(){
   const [s,inv,fs,sm,y,t,c,st,cur]=await Promise.all([loadStudents(),loadInvoices(),loadFeeStructures(),loadFinanceSummary(),loadYears(),loadTerms(),loadCurrency(),loadCMSSettings(),loadCurrentAcademicTerm()]);
   setStudents(s);setInvoices(inv);setStructures(fs);setSummary(sm);setYears(y);setTerms(t);setCurrency(c);setSchoolSettings(st);setBank(st.school_payment||{});
   if(!selectedTermId && cur?.term_id) setSelectedTermId(cur.term_id);
 }
 useEffect(()=>{refresh()},[]);
 useEffect(()=>{
   const client=createClient();
   const channel=client.channel('amqm-finance-live').on('postgres_changes',{event:'*',schema:'public',table:'payments'},()=>refresh()).on('postgres_changes',{event:'*',schema:'public',table:'student_fees'},()=>refresh()).subscribe();
   return ()=>{client.removeChannel(channel)};
 },[]);
 useEffect(()=>{if(selectedTermId){syncStudentFeeAllocations(selectedTermId).then(()=>refresh()).catch(()=>{})}},[selectedTermId]);
 const term=terms.find(t=>t.id===selectedTermId);
 const termFees=useMemo(()=>summary.fees.filter((x:any)=>x.fee_structures?.term_id===selectedTermId || (x.fee_structures?.term_id==null && x.fee_structures?.academic_year_id===term?.academic_year_id)),[summary,selectedTermId,term]);
 const byStudent=useMemo(()=>{const map=new Map<string,{due:number;paid:number}>(); for(const x of termFees){const v=map.get(x.student_id)||{due:0,paid:0};v.due+=Number(x.amount_due||0);v.paid+=Number(x.amount_paid||0);map.set(x.student_id,v)} return map},[termFees]);
 const expected=useMemo(()=>termFees.reduce((n:number,x:any)=>n+Number(x.amount_due||0),0),[termFees]);
 const collected=useMemo(()=>termFees.reduce((n:number,x:any)=>n+Number(x.amount_paid||0),0),[termFees]);
 const outstanding=Math.max(0,expected-collected);
 const statuses=useMemo(()=>{let full=0,partial=0,unpaid=0,unassigned=0; for(const s of students){const v=byStudent.get(s.id); if(!v||v.due<=0){unassigned++;continue} if(v.paid>=v.due){full++} else if(v.paid>0){partial++} else unpaid++} return {full,partial,unpaid,unassigned}},[students,byStudent]);
 async function act(fn:()=>Promise<any>,ok:string){setBusy(true);setMessage('');try{await fn();setMessage(ok);await refresh()}catch(e:any){setMessage(e?.message||'Operation failed')}finally{setBusy(false)}}
 function startEdit(f:any){setFee({id:f.id,academicYearId:f.academic_year_id,termId:f.term_id||'',section:f.section,name:f.name,amount:String(f.amount),dueDate:f.due_date||''});window.scrollTo({top:0,behavior:'smooth'})}
 async function saveBank(){await act(async()=>{await saveCMSSetting('school_payment',bank)},'Bank/payment account saved')}
 return <AdminShell title="Finance & Fees"><div className="space-y-6">
  {message&&<div className="rounded-xl border bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</div>}
  <section className="card p-5"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><div className="text-xs font-black uppercase tracking-wider text-emerald-700">Finance control center</div><h2 className="mt-1 text-2xl font-black">{term?`${term.academic_years?.name||'Academic year'} · ${termLabel(term)}`:'Select an operational term'}</h2><p className="mt-1 text-sm text-slate-500">Expected income, payments and balances update from live student fee allocations.</p></div><select className="input max-w-sm" value={selectedTermId} onChange={e=>setSelectedTermId(e.target.value)}><option value="">Select term</option>{terms.map(t=><option key={t.id} value={t.id}>{t.academic_years?.name||'Academic year'} · {termLabel(t)}</option>)}</select></div></section>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Total expected income" value={`${currency} ${expected.toLocaleString()}`}/><Kpi label="Total amount paid" value={`${currency} ${collected.toLocaleString()}`} tone="green"/><Kpi label="Outstanding balance" value={`${currency} ${outstanding.toLocaleString()}`} tone="rose"/><Kpi label="Payment records" value={summary.payments.length}/></div>
  <div className="grid gap-4 sm:grid-cols-4"><Kpi label="Paid in full" value={statuses.full} tone="green"/><Kpi label="Paid partially" value={statuses.partial} tone="amber"/><Kpi label="Not paid" value={statuses.unpaid} tone="rose"/><Kpi label="No fee assigned" value={statuses.unassigned}/></div>
  <section className="card p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="font-black">School bank & payment configuration</h2><p className="mt-1 text-xs text-slate-500">These details are used on invoices, receipts and payment instructions.</p></div><span className="pill bg-emerald-50 text-emerald-700">{currency}</span></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input className="input" placeholder="Bank name" value={bank.bank_name||''} onChange={e=>setBank({...bank,bank_name:e.target.value})}/><input className="input" placeholder="Account name" value={bank.account_name||''} onChange={e=>setBank({...bank,account_name:e.target.value})}/><input className="input" placeholder="Account number" value={bank.account_number||''} onChange={e=>setBank({...bank,account_number:e.target.value})}/><input className="input" placeholder="Transfer reference instruction" value={bank.reference_instruction||''} onChange={e=>setBank({...bank,reference_instruction:e.target.value})}/></div><button className="btn btn-primary mt-4" disabled={busy} onClick={saveBank}>Save bank configuration</button></section>
  <div className="grid gap-6 lg:grid-cols-2">
   <div className="card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-black">{fee.id?'Edit fee structure':'Set term fees'}</h2><p className="mt-1 text-xs text-slate-500">Configure Day and Boarding fees for the selected academic year and term.</p></div>{fee.id&&<button className="btn bg-slate-100" onClick={()=>setFee({id:'',academicYearId:'',termId:'',section:'day',name:'Term Fee',amount:'',dueDate:''})}>Cancel edit</button>}</div><div className="mt-4 grid gap-3 md:grid-cols-2"><select className="input" value={fee.academicYearId} onChange={e=>setFee({...fee,academicYearId:e.target.value})}><option value="">Academic year</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.is_current?' · Current':''}</option>)}</select><select className="input" value={fee.termId} onChange={e=>setFee({...fee,termId:e.target.value})}><option value="">All terms in this year</option>{terms.filter(t=>!fee.academicYearId||t.academic_year_id===fee.academicYearId).map(t=><option key={t.id} value={t.id}>{termLabel(t)}</option>)}</select><select className="input" value={fee.section} onChange={e=>setFee({...fee,section:e.target.value as any})}><option value="day">Day</option><option value="boarding">Boarding</option></select><input className="input" placeholder="Fee name" value={fee.name} onChange={e=>setFee({...fee,name:e.target.value})}/><input className="input" type="number" min="0" placeholder="Amount" value={fee.amount} onChange={e=>setFee({...fee,amount:e.target.value})}/><input className="input" type="date" value={fee.dueDate} onChange={e=>setFee({...fee,dueDate:e.target.value})}/></div><button className="btn btn-primary mt-4" disabled={busy||!fee.academicYearId||!fee.name||!fee.amount} onClick={()=>act(async()=>{if(fee.id){await updateFeeStructure(fee.id,{academicYearId:fee.academicYearId,termId:fee.termId||null,section:fee.section,name:fee.name,amount:Number(fee.amount),dueDate:fee.dueDate||null})}else{await createFeeStructure({academicYearId:fee.academicYearId,termId:fee.termId||null,section:fee.section,name:fee.name,amount:Number(fee.amount),dueDate:fee.dueDate||null})}setFee({id:'',academicYearId:fee.academicYearId,termId:fee.termId,section:fee.section,name:'Term Fee',amount:'',dueDate:''})},fee.id?'Fee structure updated':'Fee structure created')}>{fee.id?'Update fee structure':'Save fee structure'}</button></div>
   <div className="card p-5"><h2 className="text-lg font-black">Record payment</h2><p className="mt-1 text-xs text-slate-500">Payment is applied to outstanding fee lines and the finance summary refreshes immediately.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><select className="input md:col-span-2" value={payment.studentId} onChange={e=>setPayment({...payment,studentId:e.target.value})}><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.admissionNo} · {s.name} · {s.section}</option>)}</select><input className="input" type="number" min="0" placeholder="Amount" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/><select className="input" value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option>Cash</option><option>Bank transfer</option><option>Mobile money</option><option>Card</option><option>Other</option></select><input className="input" placeholder="Reference" value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/><input className="input" placeholder="Notes" value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})}/></div><button className="btn btn-primary mt-4" disabled={busy||!payment.studentId||!payment.amount} onClick={()=>act(async()=>{await recordPayment({studentId:payment.studentId,amount:Number(payment.amount),method:payment.method,reference:payment.reference,notes:payment.notes});setPayment({...payment,amount:'',reference:'',notes:''})},'Payment recorded and balances updated')}>Record payment</button></div>
  </div>
  <section className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-black">Configured fee structures</h2><p className="text-xs text-slate-500">Edit any amount or term without recreating the structure.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase"><tr><th className="p-3">Academic year</th><th>Term</th><th>Section</th><th>Name</th><th>Amount</th><th>Due</th><th/></tr></thead><tbody>{structures.map((f:any)=><tr className="border-t" key={f.id}><td className="p-3">{f.academic_years?.name||'—'}</td><td>{f.terms?.term_number?termLabel(f.terms):'All terms'}</td><td><SectionBadge section={f.section==='boarding'?'Boarding':'Day'}/></td><td>{f.name}</td><td>{currency} {Number(f.amount).toLocaleString()}</td><td>{f.due_date||'—'}</td><td><button className="btn bg-slate-100" onClick={()=>startEdit(f)}>Edit</button></td></tr>)}</tbody></table></div></section>
  <section className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-black">Student payment status</h2><p className="text-xs text-slate-500">Live status for {term?termLabel(term):'the selected term'}.</p></div><div className="divide-y">{students.map(s=>{const v=byStudent.get(s.id)||{due:0,paid:0};const bal=Math.max(0,v.due-v.paid);const state=v.due<=0?'No fee':v.paid>=v.due?'Paid in full':v.paid>0?'Partial':'Not paid';const cls=state==='Paid in full'?'bg-emerald-50 text-emerald-700':state==='Partial'?'bg-amber-50 text-amber-800':state==='Not paid'?'bg-rose-50 text-rose-700':'bg-slate-100 text-slate-500';return <div className="flex flex-col gap-3 border-b p-4 last:border-0 md:flex-row md:items-center md:justify-between" key={s.id}><div><div className="flex items-center gap-2"><b>{s.name}</b><SectionBadge section={s.section}/></div><div className="text-xs text-slate-500">{s.admissionNo} · {s.year} · {s.className||'Unassigned'}</div></div><div className="flex items-center gap-3"><div className="text-right text-xs"><div>Due <b>{currency} {v.due.toLocaleString()}</b> · Paid <b>{currency} {v.paid.toLocaleString()}</b></div><div className="text-slate-500">Balance {currency} {bal.toLocaleString()}</div></div><span className={`pill ${cls}`}>{state}</span></div></div>})}</div></section>
  <div className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-black">Next-term invoices</h2><p className="text-xs text-slate-500">Invoices generated automatically when Admin completes a term.</p></div>{invoices.map((inv:any)=><div className="flex flex-col gap-3 border-b p-4 last:border-0 md:flex-row md:items-center md:justify-between" key={inv.id}><div><div className="font-black">{inv.invoice_no}</div><div className="text-xs text-slate-500">{inv.students?.full_name||'Student'} · {inv.terms?.name||'Next term'} · Due {inv.due_date||'—'}</div></div><div className="text-right"><div className="font-black">{currency} {Number(inv.amount_due||0).toLocaleString()}</div><div className="text-xs text-slate-500">{inv.status}</div></div></div>)}{!invoices.length&&<div className="p-8 text-center text-sm text-slate-500">No next-term invoices have been generated yet.</div>}</div>
 </div></AdminShell>
}
function Kpi({label,value,tone}:{label:string;value:string|number;tone?:'green'|'rose'|'amber'}){const cls=tone==='green'?'text-emerald-700':tone==='rose'?'text-rose-600':tone==='amber'?'text-amber-700':'text-slate-950';return <div className="card p-5"><span className="text-sm text-slate-500">{label}</span><div className={`mt-2 text-2xl font-black ${cls}`}>{value}</div></div>}
