'use client';
import AdminShell from '@/components/AdminShell';
import SectionBadge from '@/components/SectionBadge';
import { loadStudents,loadInvoices } from '@/lib/live-store';
import { createFeeStructure, loadFeeStructures, loadFinanceSummary, recordPayment } from '@/lib/admin-management-store';
import { createClient } from '@/lib/supabase/client';
import { Student } from '@/lib/data';
import { useEffect, useMemo, useState } from 'react';
import {loadCMSSettings} from '@/lib/cms-live-store';

export default function Fees(){
 const [currency,setCurrency]=useState('NGN'),[schoolSettings,setSchoolSettings]=useState<any>({}); const [students,setStudents]=useState<Student[]>([]),[invoices,setInvoices]=useState<any[]>([]),[structures,setStructures]=useState<any[]>([]),[summary,setSummary]=useState<any>({fees:[],payments:[]}),[years,setYears]=useState<any[]>([]),[terms,setTerms]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [fee,setFee]=useState({academicYearId:'',termId:'',section:'day' as 'day'|'boarding',name:'Term Fee',amount:'',dueDate:''}); const [payment,setPayment]=useState({studentId:'',amount:'',method:'Cash',reference:'',notes:''});
 async function refresh(){const [s,inv,fs,sm,y,t,c,st]=await Promise.all([loadStudents(),loadInvoices(),loadFeeStructures(),loadFinanceSummary(),loadYears(),loadTerms(),loadCurrency(),loadCMSSettings()]);setStudents(s);setInvoices(inv);setStructures(fs);setSummary(sm);setYears(y);setTerms(t);setCurrency(c);setSchoolSettings(st)}
 async function loadYears(){const {data}=await createClient().from('academic_years').select('id,name,is_current').order('starts_on',{ascending:false});return data||[]}
 async function loadCurrency(){const {data}=await createClient().from('site_settings').select('value').eq('key','currency').maybeSingle();return data?.value?.symbol||data?.value?.code||'RWF'}
 async function loadTerms(){const {data}=await createClient().from('terms').select('id,name,term_number,academic_year_id').order('term_number');return data||[]}
 useEffect(()=>{refresh()},[]);
 const expected=useMemo(()=>summary.fees.reduce((n:number,x:any)=>n+Number(x.amount_due||0),0),[summary]); const collected=useMemo(()=>summary.fees.reduce((n:number,x:any)=>n+Number(x.amount_paid||0),0),[summary]); const outstanding=Math.max(0,expected-collected);
 async function act(fn:()=>Promise<any>,ok:string){setBusy(true);setMessage('');try{await fn();setMessage(ok);await refresh()}catch(e:any){setMessage(e?.message||'Operation failed')}finally{setBusy(false)}}
 return <AdminShell title="Finance & Fees"><div className="space-y-6">
  {message&&<div className="rounded-xl border bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</div>}
  <div className="grid gap-4 md:grid-cols-4"><div className="card p-5"><span className="text-sm text-slate-500">Expected</span><div className="mt-2 text-2xl font-black">{currency} {expected.toLocaleString()}</div></div><div className="card p-5"><span className="text-sm text-slate-500">Collected</span><div className="mt-2 text-2xl font-black text-emerald-700">{currency} {collected.toLocaleString()}</div></div><div className="card p-5"><span className="text-sm text-slate-500">Outstanding</span><div className="mt-2 text-2xl font-black text-rose-600">{currency} {outstanding.toLocaleString()}</div></div><div className="card p-5"><span className="text-sm text-slate-500">Payment records</span><div className="mt-2 text-2xl font-black">{summary.payments.length}</div></div></div>
  <div className="card p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-black">Invoice & payment details</h2><p className="mt-1 text-xs text-slate-500">These school account details are available to use on student invoices and receipts.</p></div><span className="pill bg-emerald-50 text-emerald-700">{currency}</span></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><b>Bank</b><br/>{schoolSettings.school_payment?.bank_name||'Not configured'}</div><div className="rounded-xl bg-slate-50 p-4"><b>Account name</b><br/>{schoolSettings.school_payment?.account_name||'Not configured'}</div><div className="rounded-xl bg-slate-50 p-4"><b>Account number</b><br/>{schoolSettings.school_payment?.account_number||'Not configured'}</div></div></div><div className="grid gap-6 lg:grid-cols-2">
   <div className="card p-5"><h2 className="text-lg font-black">Set term fees</h2><p className="mt-1 text-xs text-slate-500">Day and Boarding are fee categories on the same class structure.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><select className="input" value={fee.academicYearId} onChange={e=>setFee({...fee,academicYearId:e.target.value})}><option value="">Academic year</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.is_current?' · Current':''}</option>)}</select><select className="input" value={fee.termId} onChange={e=>setFee({...fee,termId:e.target.value})}><option value="">All terms / optional</option>{terms.filter(t=>!fee.academicYearId||t.academic_year_id===fee.academicYearId).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select className="input" value={fee.section} onChange={e=>setFee({...fee,section:e.target.value as any})}><option value="day">Day</option><option value="boarding">Boarding</option></select><input className="input" placeholder="Fee name" value={fee.name} onChange={e=>setFee({...fee,name:e.target.value})}/><input className="input" type="number" placeholder="Amount" value={fee.amount} onChange={e=>setFee({...fee,amount:e.target.value})}/><input className="input" type="date" value={fee.dueDate} onChange={e=>setFee({...fee,dueDate:e.target.value})}/></div><button className="btn btn-primary mt-4" disabled={busy||!fee.academicYearId||!fee.name||!fee.amount} onClick={()=>act(async()=>{await createFeeStructure({academicYearId:fee.academicYearId,termId:fee.termId||null,section:fee.section,name:fee.name,amount:Number(fee.amount),dueDate:fee.dueDate||null});setFee({...fee,amount:''})},'Fee structure created')}>Save fee structure</button></div>
   <div className="card p-5"><h2 className="text-lg font-black">Record payment</h2><p className="mt-1 text-xs text-slate-500">Payments are stored against the student and automatically applied to outstanding fee lines.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><select className="input md:col-span-2" value={payment.studentId} onChange={e=>setPayment({...payment,studentId:e.target.value})}><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.admissionNo} · {s.name} · {s.section}</option>)}</select><input className="input" type="number" placeholder="Amount" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/><select className="input" value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option>Cash</option><option>Bank transfer</option><option>Mobile money</option><option>Card</option><option>Other</option></select><input className="input" placeholder="Reference" value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/><input className="input" placeholder="Notes" value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})}/></div><button className="btn btn-primary mt-4" disabled={busy||!payment.studentId||!payment.amount} onClick={()=>act(async()=>{await recordPayment({studentId:payment.studentId,amount:Number(payment.amount),method:payment.method,reference:payment.reference,notes:payment.notes});setPayment({...payment,amount:'',reference:'',notes:''})},'Payment recorded')}>Record payment</button></div>
  </div>
  <div className="card p-5"><h2 className="font-black">Configured fee structures</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase"><tr><th className="p-3">Academic year</th><th>Term</th><th>Section</th><th>Name</th><th>Amount</th><th>Due</th></tr></thead><tbody>{structures.map((f:any)=><tr className="border-t" key={f.id}><td className="p-3">{f.academic_years?.name||'—'}</td><td>{f.terms?.name||'All'}</td><td><SectionBadge section={f.section==='boarding'?'Boarding':'Day'}/></td><td>{f.name}</td><td>{currency} {Number(f.amount).toLocaleString()}</td><td>{f.due_date||'—'}</td></tr>)}</tbody></table></div></div>
  <div className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-black">Next-term invoices</h2><p className="text-xs text-slate-500">Invoices generated automatically when Admin completes a term.</p></div>{invoices.map((inv:any)=><div className="flex flex-col gap-3 border-b p-4 last:border-0 md:flex-row md:items-center md:justify-between" key={inv.id}><div><div className="font-black">{inv.invoice_no}</div><div className="text-xs text-slate-500">{inv.students?.full_name||'Student'} · {inv.terms?.name||'Next term'} · Due {inv.due_date||'—'}</div></div><div className="text-right"><div className="font-black">{currency} {Number(inv.amount_due||0).toLocaleString()}</div><div className="text-xs text-slate-500">{inv.status}</div></div></div>)}{!invoices.length&&<div className="p-8 text-center text-sm text-slate-500">No next-term invoices have been generated yet.</div>}</div>
  <div className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-black">Student fee balances</h2><p className="text-xs text-slate-500">Current live balances from student fee allocations.</p></div>{students.map(s=>{const bal=Math.max(0,s.fees);return <div className="flex flex-col gap-3 border-b p-4 last:border-0 md:flex-row md:items-center md:justify-between" key={s.id}><div><div className="flex items-center gap-2"><b>{s.name}</b><SectionBadge section={s.section}/></div><div className="text-xs text-slate-500">{s.admissionNo} · {s.year} · {s.className||'Unassigned'}</div></div><b className={bal?'text-rose-600':'text-emerald-600'}>{bal?currency+' '+bal.toLocaleString():'Paid'}</b></div>})}</div>
 </div></AdminShell>
}
