'use client';
import AdminShell from '@/components/AdminShell';
import { loadAdminAlumni, loadAdminTeam, loadCMSSections, loadCMSSettings, saveAlumniProfile, saveCMSSection, saveCMSSetting, saveTeamProfile, deleteTeamProfile, deleteAlumniProfile } from '@/lib/cms-live-store';
import { createStaffAccount, loadStaffProfiles } from '@/lib/live-store';
import { useEffect, useState } from 'react';

const roles=['teacher','parent','admin','principal','finance','admissions','security'];
const teamDefaults={category:'staff',full_name:'',role_title:'',photo_url:'',brief_bio:'',full_profile:{qualifications:'',experience:'',responsibilities:''},display_on_homepage:false,published:true,sort_order:0};
export default function CMS(){
 const [sections,setSections]=useState<any[]>([]),[settings,setSettings]=useState<any>({}),[team,setTeam]=useState<any[]>([]),[alumni,setAlumni]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]),[editing,setEditing]=useState<any|null>(null),[editingSection,setEditingSection]=useState<any|null>(null),[editingSettings,setEditingSettings]=useState<any|null>(null),[account,setAccount]=useState({fullName:'',email:'',password:'',role:'teacher',phone:''}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function refresh(){const [s,st,t,a,p]=await Promise.all([loadCMSSections(true),loadCMSSettings(),loadAdminTeam(),loadAdminAlumni(),loadStaffProfiles()]);setSections(s);setSettings(st);setTeam(t);setAlumni(a);setStaff(p)} useEffect(()=>{refresh()},[]);
 async function saveSection(){if(!editingSection)return;setBusy(true);try{let content=editingSection.content;if(typeof content==='string')content=JSON.parse(content);await saveCMSSection({...editingSection,content});setEditingSection(null);setMessage('Homepage section saved to the CMS database.');await refresh()}catch(e:any){setMessage(e?.message??'Invalid section JSON or save failed.')}finally{setBusy(false)}}
 async function saveSettings(){if(!editingSettings)return;setBusy(true);try{for(const [key,value] of Object.entries(editingSettings)){await saveCMSSetting(key,value)}setEditingSettings(null);setMessage('Site settings saved.');await refresh()}catch(e:any){setMessage(e?.message??'Unable to save settings.')}finally{setBusy(false)}}
 async function saveTeam(){if(!editing)return;setBusy(true);try{await saveTeamProfile(editing);setEditing(null);setMessage('Public staff/leadership profile saved.');await refresh()}catch(e:any){setMessage(e?.message??'Unable to save profile.')}finally{setBusy(false)}}
 async function createAccount(){setBusy(true);try{const result=await createStaffAccount(account);setAccount({fullName:'',email:'',password:'',role:'teacher',phone:''});setMessage(`Account created: ${result?.email??account.email}. The user can now sign in through the portal.`);await refresh()}catch(e:any){setMessage(e?.message??'Unable to create account.')}finally{setBusy(false)}}
 return <AdminShell title="Website CMS & Staff Management"><div className="space-y-6">
  {message&&<div className="rounded-xl border bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</div>}
  <div className="card p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold">Homepage Builder</h2><p className="mt-1 text-xs text-slate-500">The public homepage content is stored in Supabase. Nothing on the homepage depends on localStorage or hard-coded school copy.</p></div><button className="btn bg-slate-100" onClick={()=>setEditingSettings({...settings})}>Edit school settings</button></div><div className="mt-5 space-y-3">{sections.map((s:any)=><div className="flex flex-col gap-3 rounded-xl border p-4 md:flex-row md:items-center" key={s.id}><div className="flex-1"><div className="text-xs font-bold uppercase tracking-wide text-slate-400">{s.section_key}</div><b>{s.title}</b><div className="text-xs text-slate-500">Order {s.sort_order} · {s.visible?'Visible':'Hidden'}</div></div><div className="flex gap-2"><button className="btn bg-slate-100" onClick={()=>setEditingSection({...s,content:JSON.stringify(s.content,null,2)})}>Edit content</button><button className="btn bg-slate-100" onClick={async()=>{await saveCMSSection({...s,visible:!s.visible});await refresh()}}>{s.visible?'Hide':'Show'}</button></div></div>)}</div></div>
  <div className="card p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Leadership, Management & Staff</h2><p className="text-xs text-slate-500">Create public profiles with photos, qualifications, experience, responsibilities, homepage visibility and publishing controls.</p></div><button className="btn btn-primary" onClick={()=>setEditing({...teamDefaults})}>+ Add public profile</button></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{team.map((t:any)=><div className="rounded-2xl border p-4" key={t.id}><div className="h-28 overflow-hidden rounded-xl bg-slate-100">{t.photo_url&&<img src={t.photo_url} alt={t.full_name} className="h-full w-full object-cover"/>}</div><div className="mt-3 text-xs uppercase text-slate-400">{t.category}</div><h3 className="font-black">{t.full_name}</h3><div className="text-sm text-emerald-800">{t.role_title}</div><p className="mt-2 text-xs text-slate-500">{t.brief_bio}</p><div className="mt-3 flex flex-wrap gap-2"><button className="btn bg-slate-100" onClick={()=>setEditing(t)}>Edit</button><button className="btn bg-slate-100" onClick={async()=>{await saveTeamProfile({...t,display_on_homepage:!t.display_on_homepage});await refresh()}}>{t.display_on_homepage?'Remove home':'Show home'}</button><button className="btn bg-rose-50 text-rose-700" onClick={async()=>{await deleteTeamProfile(t.id);await refresh()}}>Delete</button></div></div>)}</div></div>
  <div className="card p-5"><h2 className="font-bold">Staff & account management</h2><p className="mt-1 text-xs text-slate-500">Admin can create teacher, parent, finance, admissions, security and additional administrator accounts. Passwords are sent only through the secure account creation flow.</p><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-5"><input className="input" placeholder="Full name" value={account.fullName} onChange={e=>setAccount({...account,fullName:e.target.value})}/><input className="input" type="email" placeholder="Email" value={account.email} onChange={e=>setAccount({...account,email:e.target.value})}/><input className="input" type="password" placeholder="Temporary password" value={account.password} onChange={e=>setAccount({...account,password:e.target.value})}/><select className="input" value={account.role} onChange={e=>setAccount({...account,role:e.target.value})}>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select><button className="btn btn-primary" disabled={busy||!account.fullName||!account.email||account.password.length<8} onClick={createAccount}>Create account</button></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase"><tr><th className="p-3">Name</th><th>Role</th><th>Phone</th><th>Created</th></tr></thead><tbody>{staff.map((p:any)=><tr className="border-t" key={p.id}><td className="p-3 font-semibold">{p.full_name}</td><td>{p.role}</td><td>{p.phone??'—'}</td><td>{new Date(p.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></div>
  <div className="card p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Alumni publishing</h2><p className="text-xs text-slate-500">Graduation records remain private; Admin controls what is publicly published.</p></div><button className="btn btn-primary" onClick={()=>setAlumni(x=>x)}>Refresh</button></div><div className="mt-5 grid gap-3 md:grid-cols-3">{alumni.map((a:any)=><div className="rounded-xl border p-4" key={a.id}><b>{a.full_name}</b><div className="text-xs text-slate-500">{a.cohort_name} · {a.graduation_year}</div><p className="mt-2 text-sm">{a.brief_bio}</p><div className="mt-3 flex gap-2"><button className="btn bg-slate-100" onClick={async()=>{await saveAlumniProfile({...a,published:!a.published});await refresh()}}>{a.published?'Unpublish':'Publish'}</button><button className="btn bg-slate-100" onClick={async()=>{await saveAlumniProfile({...a,published_on_homepage:!a.published_on_homepage});await refresh()}}>{a.published_on_homepage?'Remove home':'Show home'}</button><button className="btn bg-rose-50 text-rose-700" onClick={async()=>{await deleteAlumniProfile(a.id);await refresh()}}>Delete</button></div></div>)}</div></div>
  {editingSection&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-4"><div className="mx-auto mt-8 w-full max-w-3xl rounded-2xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-black">Edit homepage section</h2><p className="text-xs text-slate-500">You can change every content value used by this section, including text, buttons, image URLs and item lists.</p></div><button onClick={()=>setEditingSection(null)}>✕</button></div><div className="mt-5 grid gap-3 md:grid-cols-2"><input className="input" value={editingSection.title??''} placeholder="Section title" onChange={e=>setEditingSection({...editingSection,title:e.target.value})}/><input className="input" type="number" value={editingSection.sort_order} onChange={e=>setEditingSection({...editingSection,sort_order:Number(e.target.value)})}/><label className="md:col-span-2 text-xs font-bold">Content JSON<textarea className="input mt-1 min-h-80 font-mono text-xs" value={editingSection.content} onChange={e=>setEditingSection({...editingSection,content:e.target.value})}/></label></div><div className="mt-5 flex justify-end gap-2"><button className="btn bg-slate-100" onClick={()=>setEditingSection(null)}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={saveSection}>Save section</button></div></div></div>}
  {editingSettings&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-4"><div className="mx-auto mt-8 w-full max-w-2xl rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-black">School identity & site settings</h2><button onClick={()=>setEditingSettings(null)}>✕</button></div><div className="mt-5 space-y-4">{Object.entries(editingSettings).map(([key,value]:any)=><label key={key} className="block text-xs font-bold">{key}<textarea className="input mt-1 min-h-24 font-mono text-xs" value={JSON.stringify(value,null,2)} onChange={e=>{try{setEditingSettings({...editingSettings,[key]:JSON.parse(e.target.value)})}catch{}}}/></label>)}</div><div className="mt-5 flex justify-end gap-2"><button className="btn bg-slate-100" onClick={()=>setEditingSettings(null)}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={saveSettings}>Save settings</button></div></div></div>}
  {editing&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-4"><div className="mx-auto mt-8 w-full max-w-2xl rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-black">Public profile editor</h2><button onClick={()=>setEditing(null)}>✕</button></div><div className="mt-5 grid gap-3 md:grid-cols-2"><select className="input" value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}><option>leadership</option><option>management</option><option>staff</option></select><input className="input" placeholder="Full name" value={editing.full_name} onChange={e=>setEditing({...editing,full_name:e.target.value})}/><input className="input" placeholder="Role title" value={editing.role_title} onChange={e=>setEditing({...editing,role_title:e.target.value})}/><input className="input" placeholder="Photo URL" value={editing.photo_url??''} onChange={e=>setEditing({...editing,photo_url:e.target.value})}/><textarea className="input md:col-span-2" placeholder="Brief biography" value={editing.brief_bio??''} onChange={e=>setEditing({...editing,brief_bio:e.target.value})}/><textarea className="input md:col-span-2 min-h-32 font-mono text-xs" value={JSON.stringify(editing.full_profile??{},null,2)} onChange={e=>{try{setEditing({...editing,full_profile:JSON.parse(e.target.value)})}catch{}}}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!editing.published} onChange={e=>setEditing({...editing,published:e.target.checked})}/> Published</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!editing.display_on_homepage} onChange={e=>setEditing({...editing,display_on_homepage:e.target.checked})}/> Show on homepage</label></div><div className="mt-5 flex justify-end gap-2"><button className="btn bg-slate-100" onClick={()=>setEditing(null)}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={saveTeam}>Save profile</button></div></div></div>}
 </div></AdminShell>
}
