'use client';
import AdminShell from '@/components/AdminShell';
import { loadAdminAlumni, loadAdminHomepageMedia, loadAdminTeam, loadCMSSections, loadCMSSettings, saveAlumniProfile, saveCMSSection, saveCMSSetting, saveHomepageMedia, deleteHomepageMedia, saveTeamProfile, deleteTeamProfile, deleteAlumniProfile } from '@/lib/cms-live-store';
import { createStaffAccount, loadStaffProfiles, updateStaffProfile } from '@/lib/live-store';
import { deletePublicMedia, uploadPublicMedia } from '@/lib/admin-management-store';
import { useEffect, useMemo, useState } from 'react';

const roles=['teacher','admin','principal','finance','admissions','security','parent'];
const categories=['Student Activities','Classrooms','School Compound','Qur\'an Recitations','Prayer & Worship','Teachers Teaching','Student Hostels','Other'];
const tabs=[['website','School & Navigation'],['homepage','Homepage Content'],['media','Photos & Videos'],['staff','Staff'],['alumni','Alumni']];
const teamDefaults={category:'staff',full_name:'',role_title:'',photo_url:'',brief_bio:'',full_profile:{qualifications:'',experience:'',responsibilities:''},display_on_homepage:false,published:true,sort_order:0};

function rowsToItems(value:string){return value.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const [a,b,c,d]=line.split('|').map(x=>x.trim());return {title:a||'',text:b||'',icon:c||'star',image:d||''};});}
function itemsToRows(items:any[]){return (items||[]).map(x=>[x.title||x.label||'',x.text||x.description||'',x.icon||'',x.image||''].join(' | ')).join('\n');}

export default function CMS(){
 const [tab,setTab]=useState('website'),[sections,setSections]=useState<any[]>([]),[settings,setSettings]=useState<any>({}),[team,setTeam]=useState<any[]>([]),[alumni,setAlumni]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]),[media,setMedia]=useState<any[]>([]);
 const [editing,setEditing]=useState<any|null>(null),[editingSection,setEditingSection]=useState<any|null>(null),[account,setAccount]=useState({fullName:'',email:'',password:'',role:'teacher',phone:'',jobTitle:'',department:'',joinedOn:''});
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [editingMedia,setEditingMedia]=useState<any|null>(null),[mediaFilter,setMediaFilter]=useState('All');
 const [identity,setIdentity]=useState({schoolName:'',shortName:'AMQM',tagline:'',logoUrl:'',phone:'',email:'',address:'',website:'',facebook:'',instagram:'',youtube:'',whatsapp:'',tiktok:'',currency:'NGN'});
 const [mediaDraft,setMediaDraft]=useState({title:'',description:'',category:'Student Activities',customCategory:'',file:null as File|null,sortOrder:1});
 const sectionMap=useMemo(()=>Object.fromEntries(sections.map(x=>[x.section_key,x])),[sections]);
 async function refresh(){const [s,st,t,a,p,m]=await Promise.all([loadCMSSections(true),loadCMSSettings(),loadAdminTeam(),loadAdminAlumni(),loadStaffProfiles(),loadAdminHomepageMedia()]);setSections(s);setSettings(st);setTeam(t);setAlumni(a);setStaff(p);setMedia(m);setIdentity({schoolName:st.school_name?.value??'',shortName:st.short_name?.value??'AMQM',tagline:st.tagline?.value??'',logoUrl:st.logo_url?.value??'',phone:st.contact?.phone??'',email:st.contact?.email??'',address:st.contact?.address??'',website:st.contact?.website??'',facebook:st.social_links?.facebook??'',instagram:st.social_links?.instagram??'',youtube:st.social_links?.youtube??'',whatsapp:st.social_links?.whatsapp??'',tiktok:st.social_links?.tiktok??'',currency:st.currency?.code??'NGN'})}
 useEffect(()=>{refresh()},[]);
 async function run(fn:()=>Promise<any>,ok:string){setBusy(true);setMessage('');try{await fn();setMessage(ok);await refresh()}catch(e:any){setMessage(e?.message||'Operation failed')}finally{setBusy(false)}}
 async function saveIdentity(){await run(async()=>Promise.all([saveCMSSetting('school_name',{value:identity.schoolName}),saveCMSSetting('short_name',{value:identity.shortName}),saveCMSSetting('tagline',{value:identity.tagline}),saveCMSSetting('logo_url',{value:identity.logoUrl}),saveCMSSetting('contact',{phone:identity.phone,email:identity.email,address:identity.address,website:identity.website}),saveCMSSetting('social_links',{facebook:identity.facebook,instagram:identity.instagram,youtube:identity.youtube,whatsapp:identity.whatsapp,tiktok:identity.tiktok}),saveCMSSetting('currency',{code:identity.currency,symbol:identity.currency})]),'School settings saved.')}
 async function uploadLogo(file:File|null){if(!file)return;await run(async()=>{const m=await uploadPublicMedia(file,{altText:'School logo'});await saveCMSSetting('logo_url',{value:m.public_url})},'Logo uploaded and published.')}
 async function uploadHomepageMedia(){const file=mediaDraft.file;if(!file||!mediaDraft.title.trim())return;if(file.size>80*1024*1024){setMessage('Please choose an image or video smaller than 80 MB.');return;}await run(async()=>{const m=await uploadPublicMedia(file,{altText:mediaDraft.title,caption:mediaDraft.description});await saveHomepageMedia({title:mediaDraft.title,description:mediaDraft.description,category:mediaDraft.category==='Other'?mediaDraft.customCategory:mediaDraft.category,media_type:file.type.startsWith('video/')?'video':'image',public_url:m.public_url,storage_path:m.storage_path,alt_text:mediaDraft.title,visible:true,sort_order:mediaDraft.sortOrder});setMediaDraft({title:'',description:'',category:'Student Activities',customCategory:'',file:null,sortOrder:media.length+2})},'Homepage media added.')}
 async function removeMedia(item:any){await run(async()=>{if(item.storage_path){try{await deletePublicMedia({id:'',storage_path:item.storage_path})}catch{}} await deleteHomepageMedia(item.id)},'Homepage media deleted.')}
 async function toggleMedia(item:any){await run(()=>saveHomepageMedia({...item,visible:!item.visible}),item.visible?'Media hidden from homepage.':'Media published on homepage.')}
 async function saveEditedMedia(){if(!editingMedia)return;const replacement=editingMedia.replacementFile as File|null;if(replacement&&replacement.size>80*1024*1024){setMessage('Please choose a replacement file smaller than 80 MB.');return;}await run(async()=>{let next={...editingMedia};delete next.replacementFile;if(replacement){const uploaded=await uploadPublicMedia(replacement,{altText:next.title,caption:next.description});next={...next,media_type:replacement.type.startsWith('video/')?'video':'image',public_url:uploaded.public_url,storage_path:uploaded.storage_path};if(editingMedia.storage_path){try{await deletePublicMedia({id:'',storage_path:editingMedia.storage_path})}catch{}}}await saveHomepageMedia(next)},'Media updated and published.');setEditingMedia(null)}
 async function saveSection(){if(!editingSection)return;await run(async()=>{let content=editingSection.content; if(typeof content==='string')content=JSON.parse(content); await saveCMSSection({...editingSection,content})},'Homepage section saved.');setEditingSection(null)}
 async function saveTeam(){if(!editing)return;await run(()=>saveTeamProfile(editing),'Public staff profile saved.');setEditing(null)}
 async function createAccount(){await run(async()=>{const r=await createStaffAccount(account);setAccount({fullName:'',email:'',password:'',role:'teacher',phone:'',jobTitle:'',department:'',joinedOn:''});setMessage(`Account created. Staff ID: ${r?.staff_id||'assigned automatically'}.`);},'Staff account created.');}
 async function editStaff(p:any){const next=window.prompt('Employment status: active, inactive, suspended or left',p.employment_status||'active');if(!next||!['active','inactive','suspended','left'].includes(next))return;await run(()=>updateStaffProfile(p.id,{employment_status:next}),`${p.full_name} updated.`)}
 const sectionLabels:{[k:string]:string}={hero:'Hero / first impression',features:'Why choose AMQM',about:'About the school',mission_vision:'Mission & Vision',stats:'School at a glance',programme:'Programme',values:'Values',campuses:'Campus highlights',news:'News & Events',footer:'Footer'};
 return <AdminShell title="Website CMS & Administration"><div className="space-y-6">
   <section className="overflow-hidden rounded-[2rem] bg-gradient-to-r from-[#06372f] via-emerald-900 to-[#9b7622] p-6 text-white shadow-xl md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[11px] font-black uppercase tracking-[.24em] text-amber-300">AMQM Website Studio</div><h2 className="mt-2 text-3xl font-black">Make the public website sell the school.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-50/75">Every public-facing homepage section is database-driven. Admin controls the content, photos, videos, staff profiles and publishing state; teachers and parents never receive CMS access.</p></div><a href="/" target="_blank" className="btn shrink-0 bg-white text-emerald-950">Preview website ↗</a></div></section>
   {message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{message}</div>}
   <div className="flex gap-2 overflow-x-auto border-b pb-2">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-black ${tab===id?'bg-[#06372f] text-white':'bg-slate-100 text-slate-700'}`}>{label}</button>)}</div>

   {tab==='website'&&<div className="space-y-5"><div className="card p-6"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><h2 className="text-xl font-black">School identity & branding</h2><p className="mt-1 text-sm text-slate-500">Change the name, logo, contact details and public social links without touching code.</p></div><label className="btn btn-primary cursor-pointer">Upload logo<input hidden type="file" accept="image/*" onChange={e=>uploadLogo(e.target.files?.[0]||null)}/></label></div><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-xs font-bold">Official school name<input className="input mt-1" value={identity.schoolName} onChange={e=>setIdentity({...identity,schoolName:e.target.value})}/></label><label className="text-xs font-bold">Short name<input className="input mt-1" value={identity.shortName} onChange={e=>setIdentity({...identity,shortName:e.target.value})}/></label><label className="text-xs font-bold md:col-span-2">Tagline<input className="input mt-1" value={identity.tagline} onChange={e=>setIdentity({...identity,tagline:e.target.value})}/></label><label className="text-xs font-bold">Phone<input className="input mt-1" value={identity.phone} onChange={e=>setIdentity({...identity,phone:e.target.value})}/></label><label className="text-xs font-bold">Email<input className="input mt-1" value={identity.email} onChange={e=>setIdentity({...identity,email:e.target.value})}/></label><label className="text-xs font-bold md:col-span-2">Address<input className="input mt-1" value={identity.address} onChange={e=>setIdentity({...identity,address:e.target.value})}/></label><label className="text-xs font-bold">Website<input className="input mt-1" value={identity.website} onChange={e=>setIdentity({...identity,website:e.target.value})}/></label><label className="text-xs font-bold">Currency<input className="input mt-1" value={identity.currency} onChange={e=>setIdentity({...identity,currency:e.target.value.toUpperCase()})}/></label></div><button className="btn btn-primary mt-5" disabled={busy} onClick={saveIdentity}>{busy?'Saving…':'Save school settings'}</button></div>
   <div className="card p-6"><h2 className="text-xl font-black">Public navigation</h2><p className="mt-1 text-sm text-slate-500">These are the links visitors see. The public Programs page is separate from the private Program & Academic Setup admin page.</p><div className="mt-4 grid gap-2 md:grid-cols-2">{(settings.nav?.links||defaultNav()).map((x:any,i:number)=><div key={i} className="flex items-center justify-between rounded-xl border p-3"><div><b>{x.label}</b><div className="text-xs text-slate-400">{x.href}</div></div><span className="pill bg-emerald-50 text-emerald-700">Public</span></div>)}</div></div></div>}

   {tab==='homepage'&&<div className="space-y-4"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Editing rule:</b> this area changes what everyone sees on the public homepage. Media has its own dedicated tab so Admin can upload, rename, publish, hide or delete images/videos without copying URLs.</div>{Object.entries(sectionMap).sort((a:any,b:any)=>a[1].sort_order-b[1].sort_order).map(([key,s]:any)=><div className="card flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between" key={key}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="pill bg-emerald-50 text-emerald-700">{key}</span><span className={`pill ${s.visible?'bg-green-50 text-green-700':'bg-slate-100 text-slate-500'}`}>{s.visible?'Published':'Hidden'}</span></div><h3 className="mt-2 text-lg font-black">{sectionLabels[key]||s.title||key}</h3><p className="mt-1 text-sm text-slate-500">{s.title||'No section title configured'}</p></div><div className="flex shrink-0 gap-2"><button className="btn bg-slate-100" onClick={()=>setEditingSection({...s,content:JSON.stringify(s.content||{},null,2)})}>Edit</button><button className="btn bg-emerald-50 text-emerald-800" onClick={()=>run(()=>saveCMSSection({...s,visible:!s.visible}),s.visible?'Section hidden.':'Section published.')}>{s.visible?'Hide':'Publish'}</button></div></div>)}</div>}

   {tab==='media'&&<div className="space-y-5"><div className="card overflow-hidden"><div className="bg-gradient-to-r from-emerald-950 to-emerald-800 p-6 text-white"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.2em] text-amber-300">Visual library</div><h2 className="mt-1 text-2xl font-black">Photos & Videos</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-emerald-50/70">Upload the real school story here. Every published item can appear on the public homepage without touching code.</p></div><div className="rounded-2xl bg-white/10 px-4 py-3 text-sm font-bold">{media.length} media items · {media.filter((x:any)=>x.visible).length} published</div></div></div><div className="p-6"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><label className="rounded-xl border-2 border-dashed border-emerald-200 bg-emerald-50/40 p-4 text-sm font-bold text-emerald-950">Media file<label className="btn mt-2 block cursor-pointer bg-white text-center shadow-sm">Choose image/video<input hidden type="file" accept="image/*,video/*" onChange={e=>setMediaDraft({...mediaDraft,file:e.target.files?.[0]||null})}/></label><div className="mt-2 truncate text-xs font-medium text-slate-500">{mediaDraft.file?.name||'No file selected'} · max 80 MB</div></label><input className="input" placeholder="Heading / title" value={mediaDraft.title} onChange={e=>setMediaDraft({...mediaDraft,title:e.target.value})}/><select className="input" value={mediaDraft.category} onChange={e=>setMediaDraft({...mediaDraft,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select><input className="input" type="number" min="0" value={mediaDraft.sortOrder} onChange={e=>setMediaDraft({...mediaDraft,sortOrder:Number(e.target.value)})}/><textarea className="input md:col-span-2 lg:col-span-3" placeholder="Short description shown on the homepage" value={mediaDraft.description} onChange={e=>setMediaDraft({...mediaDraft,description:e.target.value})}/>{mediaDraft.category==='Other'&&<input className="input" placeholder="Custom category" value={mediaDraft.customCategory} onChange={e=>setMediaDraft({...mediaDraft,customCategory:e.target.value})}/>}</div><button className="btn btn-primary mt-4" disabled={busy||!mediaDraft.file||!mediaDraft.title.trim()} onClick={uploadHomepageMedia}>{busy?'Uploading…':'Upload & publish to homepage'}</button></div></div>
   <div className="flex flex-wrap gap-2">{['All',...categories].map((cat)=><button key={cat} onClick={()=>setMediaFilter(cat)} className={`rounded-full px-4 py-2 text-xs font-black ${mediaFilter===cat?'bg-emerald-950 text-white':'bg-slate-100 text-slate-600'}`}>{cat}</button>)}</div>
   <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{media.filter((item:any)=>mediaFilter==='All'||item.category===mediaFilter).map((item:any)=><article key={item.id} className="card overflow-hidden transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-56 bg-emerald-950">{item.media_type==='video'?<video src={item.public_url} controls preload="metadata" className="h-full w-full object-cover"/>:<img src={item.public_url} alt={item.alt_text||item.title} className="h-full w-full object-cover"/>}<div className="absolute left-3 top-3 rounded-full bg-black/65 px-3 py-1 text-[10px] font-black uppercase text-white">{item.category}</div><div className={`absolute right-3 top-3 rounded-full px-3 py-1 text-[10px] font-black uppercase ${item.visible?'bg-emerald-400 text-emerald-950':'bg-white/90 text-slate-600'}`}>{item.visible?'Published':'Hidden'}</div></div><div className="p-5"><h3 className="font-black text-emerald-950">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description||'No description'}</p><div className="mt-4 flex flex-wrap gap-2"><button className="btn bg-slate-100" onClick={()=>toggleMedia(item)}>{item.visible?'Hide':'Publish'}</button><button className="btn bg-slate-100" onClick={()=>setEditingMedia({...item,replacementFile:null})}>Edit / replace</button><button className="btn bg-rose-50 text-rose-700" onClick={()=>removeMedia(item)}>Delete</button></div></div></article>)}</div></div>}

   {tab==='staff'&&<div className="space-y-5"><div className="card p-6"><h2 className="text-xl font-black">Staff accounts</h2><p className="mt-1 text-sm text-slate-500">Create staff accounts here. Teachers still receive a separate restricted portal.</p><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{[['Full name','fullName'],['Email','email'],['Temporary password','password'],['Phone','phone'],['Job title','jobTitle'],['Department','department'],['Joined on','joinedOn']].map(([label,key])=><input key={key} className="input" placeholder={label} type={key==='password'?'password':key==='joinedOn'?'date':'text'} value={(account as any)[key]} onChange={e=>setAccount({...account,[key]:e.target.value})}/>)}<select className="input" value={account.role} onChange={e=>setAccount({...account,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></div><button className="btn btn-primary mt-4" disabled={busy||!account.fullName||!account.email||account.password.length<8} onClick={createAccount}>Create staff account</button></div><div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase"><tr><th className="p-3">Staff ID</th><th>Name</th><th>Role</th><th>Job title</th><th>Department</th><th>Status</th><th/></tr></thead><tbody>{staff.filter((p:any)=>p.role!=='parent').map((p:any)=><tr className="border-t" key={p.id}><td className="p-3 font-black text-emerald-800">{p.staff_id||'Pending'}</td><td className="font-semibold">{p.full_name}</td><td>{p.role}</td><td>{p.job_title||'—'}</td><td>{p.department||'—'}</td><td><span className="pill bg-slate-100">{p.employment_status||'active'}</span></td><td><button className="btn bg-slate-100" onClick={()=>editStaff(p)}>Change status</button></td></tr>)}</tbody></table></div></div><div className="card p-6"><h2 className="font-black">Public staff profiles</h2><p className="mt-1 text-sm text-slate-500">Only profiles marked published and show on homepage appear publicly.</p><button className="btn btn-primary mt-3" onClick={()=>{const fresh={...teamDefaults,id:crypto.randomUUID()};setEditing(fresh)}}>Add public profile</button><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{team.map((p:any)=><div key={p.id} className="rounded-2xl border p-4"><div className="font-black">{p.full_name}</div><div className="text-sm text-emerald-700">{p.role_title}</div><div className="mt-2 text-xs text-slate-500">{p.published?'Published':'Hidden'} · {p.display_on_homepage?'Homepage':'Profile only'}</div><div className="mt-3 flex gap-2"><button className="btn bg-slate-100" onClick={()=>setEditing(p)}>Edit</button><button className="btn bg-rose-50 text-rose-700" onClick={()=>run(()=>deleteTeamProfile(p.id),'Public profile deleted.')}>Delete</button></div></div>)}</div></div></div>}

   {tab==='alumni'&&<div className="card p-6"><h2 className="text-xl font-black">Alumni publishing</h2><p className="mt-1 text-sm text-slate-500">Admin controls what becomes public.</p><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{alumni.map((a:any)=><div className="rounded-2xl border p-5" key={a.id}><b>{a.full_name}</b><div className="text-xs text-slate-500">{a.cohort_name} · {a.graduation_year}</div><p className="mt-2 text-sm">{a.brief_bio}</p><div className="mt-4 flex flex-wrap gap-2"><button className="btn bg-slate-100" onClick={()=>run(()=>saveAlumniProfile({...a,published:!a.published}),a.published?'Unpublished.':'Published.')}>{a.published?'Unpublish':'Publish'}</button><button className="btn bg-slate-100" onClick={()=>run(()=>saveAlumniProfile({...a,published_on_homepage:!a.published_on_homepage}),a.published_on_homepage?'Removed from homepage.':'Shown on homepage.')}>{a.published_on_homepage?'Remove home':'Show home'}</button><button className="btn bg-rose-50 text-rose-700" onClick={()=>run(()=>deleteAlumniProfile(a.id),'Alumni record deleted.')}>Delete</button></div></div>)}</div></div>}

   {editingSection&&<SectionEditor section={editingSection} setSection={setEditingSection} save={saveSection} busy={busy} media={media}/>} 
   {editingMedia&&<div className="fixed inset-0 z-[110] overflow-y-auto bg-slate-950/60 p-4"><div className="mx-auto my-8 w-full max-w-xl rounded-[2rem] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><div className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Media item</div><h2 className="mt-1 text-2xl font-black">Edit homepage media</h2></div><button className="btn bg-slate-100" onClick={()=>setEditingMedia(null)}>Close</button></div><div className="mt-6 space-y-3"><div className="overflow-hidden rounded-2xl bg-slate-100">{editingMedia.media_type==='video'?<video src={editingMedia.public_url} controls preload="metadata" className="h-48 w-full object-cover"/>:<img src={editingMedia.public_url} alt="" className="h-48 w-full object-cover"/>}</div><label className="text-xs font-bold">Replace file (optional)<label className="btn mt-1 block cursor-pointer bg-emerald-50 text-center text-emerald-900">Choose new image/video<input hidden type="file" accept="image/*,video/*" onChange={e=>setEditingMedia({...editingMedia,replacementFile:e.target.files?.[0]||null})}/></label><div className="mt-1 text-xs text-slate-500">{editingMedia.replacementFile?.name||'Keep current file'} · max 80 MB</div></label><input className="input" placeholder="Heading / title" value={editingMedia.title||''} onChange={e=>setEditingMedia({...editingMedia,title:e.target.value})}/><select className="input" value={categories.includes(editingMedia.category)?editingMedia.category:'Other'} onChange={e=>setEditingMedia({...editingMedia,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select><textarea className="input min-h-28" placeholder="Description" value={editingMedia.description||''} onChange={e=>setEditingMedia({...editingMedia,description:e.target.value})}/><input className="input" type="number" min="0" value={editingMedia.sort_order||0} onChange={e=>setEditingMedia({...editingMedia,sort_order:Number(e.target.value)})}/><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={!!editingMedia.visible} onChange={e=>setEditingMedia({...editingMedia,visible:e.target.checked})}/> Show on homepage</label></div><div className="mt-6 flex justify-end gap-2"><button className="btn bg-slate-100" onClick={()=>setEditingMedia(null)}>Cancel</button><button className="btn btn-primary" disabled={busy||!editingMedia.title} onClick={saveEditedMedia}>Save changes</button></div></div></div>}
   {editing&&<TeamEditor profile={editing} setProfile={setEditing} save={saveTeam} busy={busy}/>} 
 </div></AdminShell>
}

function SectionEditor({section,setSection,save,busy,media}:{section:any;setSection:(x:any)=>void;save:()=>void;busy:boolean;media:any[]}){
 let content:any={};try{content=typeof section.content==='string'?JSON.parse(section.content):section.content||{}}catch{}
 const key=section.section_key;
 const set=(k:string,v:any)=>setSection({...section,content:JSON.stringify({...content,[k]:v},null,2)});
 const rows=Array.isArray(content.items)?itemsToRows(content.items):'';
 return <div className="fixed inset-0 z-[100] overflow-y-auto bg-slate-950/60 p-4"><div className="mx-auto my-6 w-full max-w-5xl rounded-[2rem] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Homepage editor</div><h2 className="mt-1 text-2xl font-black">{section.section_key}</h2><p className="mt-1 text-sm text-slate-500">Edit the visible content below. Media is uploaded from the Photos & Videos tab.</p></div><button className="btn bg-slate-100" onClick={()=>setSection(null)}>Close</button></div><div className="mt-6 grid gap-4 md:grid-cols-2">
   <label className="text-xs font-bold">Section title<input className="input mt-1" value={section.title||''} onChange={e=>setSection({...section,title:e.target.value})}/></label><label className="text-xs font-bold">Sort order<input className="input mt-1" type="number" value={section.sort_order} onChange={e=>setSection({...section,sort_order:Number(e.target.value)})}/></label>{key==='hero'&&<><label className="text-xs font-bold">Hero image<select className="input mt-1" value={content.hero_image||''} onChange={e=>set('hero_image',e.target.value)}><option value="">No image</option>{media.filter((x:any)=>x.media_type==='image').map((x:any)=><option key={x.id} value={x.public_url}>{x.title} · {x.category}</option>)}</select></label><label className="text-xs font-bold">Hero video<select className="input mt-1" value={content.hero_video||''} onChange={e=>set('hero_video',e.target.value)}><option value="">No video</option>{media.filter((x:any)=>x.media_type==='video').map((x:any)=><option key={x.id} value={x.public_url}>{x.title}</option>)}</select></label></>}
   {key==='hero'&&<><Field label="Eyebrow" value={content.eyebrow||''} set={v=>set('eyebrow',v)}/><Field label="Hero title" value={content.title||''} set={v=>set('title',v)}/><TextField label="Hero subtitle" value={content.subtitle||''} set={v=>set('subtitle',v)}/><Field label="Quote" value={content.quote||''} set={v=>set('quote',v)}/><Field label="Quote source" value={content.quote_source||''} set={v=>set('quote_source',v)}/><Field label="Primary CTA" value={content.primary_cta||''} set={v=>set('primary_cta',v)}/><Field label="Primary link" value={content.primary_href||'/admissions'} set={v=>set('primary_href',v)}/><Field label="Secondary CTA" value={content.secondary_cta||''} set={v=>set('secondary_cta',v)}/><Field label="Secondary link" value={content.secondary_href||'/about'} set={v=>set('secondary_href',v)}/></>}
   {key==='about'&&<><Field label="Heading" value={content.title||''} set={v=>set('title',v)}/><TextField label="About text" value={content.text||''} set={v=>set('text',v)}/><Field label="Button text" value={content.cta||''} set={v=>set('cta',v)}/><Field label="Button link" value={content.cta_href||'/about'} set={v=>set('cta_href',v)}/><label className="text-xs font-bold">About image<select className="input mt-1" value={content.image||''} onChange={e=>set('image',e.target.value)}><option value="">No image</option>{media.filter((x:any)=>x.media_type==='image').map((x:any)=><option key={x.id} value={x.public_url}>{x.title} · {x.category}</option>)}</select></label><label className="text-xs font-bold">About video<select className="input mt-1" value={content.video||''} onChange={e=>set('video',e.target.value)}><option value="">No video</option>{media.filter((x:any)=>x.media_type==='video').map((x:any)=><option key={x.id} value={x.public_url}>{x.title}</option>)}</select></label></>}
   {key==='mission_vision'&&<><Field label="Mission heading" value={content.mission_title||'Our Mission'} set={v=>set('mission_title',v)}/><TextField label="Mission" value={content.mission||''} set={v=>set('mission',v)}/><Field label="Vision heading" value={content.vision_title||'Our Vision'} set={v=>set('vision_title',v)}/><TextField label="Vision" value={content.vision||''} set={v=>set('vision',v)}/></>}
   {key==='features'&&<><div className="md:col-span-2"><label className="text-xs font-bold">Feature cards <span className="font-normal text-slate-400">one per line: Title | Description | Icon</span><textarea className="input mt-1 min-h-52" value={rows} onChange={e=>set('items',rowsToItems(e.target.value))}/></label></div></>}
   {key==='stats'&&<div className="md:col-span-2"><label className="text-xs font-bold">Statistics <span className="font-normal text-slate-400">one per line: Value | Label</span><textarea className="input mt-1 min-h-40" value={(content.items||[]).map((x:any)=>`${x.value||''} | ${x.label||''}`).join('\n')} onChange={e=>set('items',e.target.value.split('\n').map(x=>{const [value,label]=x.split('|').map(y=>y.trim());return {value,label}}).filter(x=>x.value||x.label))}/></label></div>}
   {key==='values'&&<div className="md:col-span-2"><label className="text-xs font-bold">Values <span className="font-normal text-slate-400">comma separated</span><input className="input mt-1" value={(content.items||[]).map((x:any)=>typeof x==='string'?x:x.label).join(', ')} onChange={e=>set('items',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label></div>}
   {(key==='programme'||key==='campuses'||key==='news'||key==='footer')&&<><Field label="Heading" value={content.title||''} set={v=>set('title',v)}/><TextField label="Description" value={content.text||content.tagline||''} set={v=>set(key==='footer'?'tagline':'text',v)}/><div className="md:col-span-2"><label className="text-xs font-bold">Items / advanced content <span className="font-normal text-slate-400">JSON for this section; use Photos & Videos for direct media uploads.</span><textarea className="input mt-1 min-h-48 font-mono text-xs" value={JSON.stringify(content.items||[],null,2)} onChange={e=>{try{set('items',JSON.parse(e.target.value))}catch{}}}/></label></div></>}
   {['hero','about'].includes(key)&&<div className="md:col-span-2 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600"><b>Media:</b> Upload or replace the hero/about image/video in the <span className="font-bold text-emerald-800">Photos & Videos</span> tab, then use the saved public media item there. This keeps all files in the admin-managed media library.</div>}
 </div><div className="mt-6 flex justify-end gap-2"><button className="btn bg-slate-100" onClick={()=>setSection(null)}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={save}>Save homepage section</button></div></div></div>
}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="text-xs font-bold">{label}<input className="input mt-1" value={value} onChange={e=>set(e.target.value)}/></label>}
function TextField({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="text-xs font-bold md:col-span-2">{label}<textarea className="input mt-1 min-h-28" value={value} onChange={e=>set(e.target.value)}/></label>}
function TeamEditor({profile,setProfile,save,busy}:{profile:any;setProfile:(x:any)=>void;save:()=>void;busy:boolean}){return <div className="fixed inset-0 z-[100] overflow-y-auto bg-slate-950/60 p-4"><div className="mx-auto my-6 w-full max-w-3xl rounded-[2rem] bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><div className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Public profile</div><h2 className="mt-1 text-2xl font-black">{profile.full_name||'New profile'}</h2></div><button className="btn bg-slate-100" onClick={()=>setProfile(null)}>Close</button></div><div className="mt-6 grid gap-3 md:grid-cols-2"><select className="input" value={profile.category||'staff'} onChange={e=>setProfile({...profile,category:e.target.value})}><option>leadership</option><option>management</option><option>staff</option></select><input className="input" placeholder="Full name" value={profile.full_name||''} onChange={e=>setProfile({...profile,full_name:e.target.value})}/><input className="input" placeholder="Role title" value={profile.role_title||''} onChange={e=>setProfile({...profile,role_title:e.target.value})}/><textarea className="input md:col-span-2" placeholder="Brief biography" value={profile.brief_bio||''} onChange={e=>setProfile({...profile,brief_bio:e.target.value})}/><textarea className="input md:col-span-2 min-h-32 font-mono text-xs" value={JSON.stringify(profile.full_profile||{},null,2)} onChange={e=>{try{setProfile({...profile,full_profile:JSON.parse(e.target.value)})}catch{}}}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!profile.published} onChange={e=>setProfile({...profile,published:e.target.checked})}/> Published</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!profile.display_on_homepage} onChange={e=>setProfile({...profile,display_on_homepage:e.target.checked})}/> Show on homepage</label></div><div className="mt-6 flex justify-end gap-2"><button className="btn bg-slate-100" onClick={()=>setProfile(null)}>Cancel</button><button className="btn btn-primary" disabled={busy||!profile.full_name} onClick={save}>Save profile</button></div></div></div>}
function defaultNav(){return [{label:'Home',href:'/'},{label:'About Us',href:'/about'},{label:'Programs',href:'/programs'},{label:'Admissions',href:'/admissions'},{label:'Campus Life',href:'/campus-life'},{label:'News & Events',href:'/news'},{label:'Contact Us',href:'/contact'}]}
