'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { loadCMSSections, loadCMSSettings, loadPublicAlumni, loadPublicTeam, type CMSSection } from '@/lib/cms-live-store';

function sectionMap(sections: CMSSection[]){ return Object.fromEntries(sections.map(s=>[s.section_key,s])); }
export default function Home(){
 const [sections,setSections]=useState<CMSSection[]>([]),[settings,setSettings]=useState<Record<string,any>>({}),[team,setTeam]=useState<any[]>([]),[alumni,setAlumni]=useState<any[]>([]);
 useEffect(()=>{Promise.all([loadCMSSections(),loadCMSSettings(),loadPublicTeam(),loadPublicAlumni()]).then(([s,st,t,a])=>{setSections(s);setSettings(st);setTeam(t);setAlumni(a)})},[]);
 const m=useMemo(()=>sectionMap(sections),[sections]); const hero=m.hero?.content??{}; const features=m.features?.content?.items??[]; const about=m.about?.content??{}; const stats=m.stats?.content?.items??[]; const programme=m.programme?.content??{}; const values=m.values?.content?.items??[]; const campuses=m.campuses?.content?.items??[]; const news=m.news?.content?.items??[]; const footer=m.footer?.content??{}; const nav=settings.nav?.links??[]; const contact=settings.contact??{};
 return <main className="min-h-screen bg-white text-slate-900">
  <div className="bg-[#064e3b] px-4 py-2 text-center text-xs text-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3"><span>{settings.school_name?.value??'Quran Memorization School'}</span><span className="hidden sm:block">{contact.phone??''} · {contact.email??''}</span><div className="flex gap-3"><Link href="/auth/login">Parents Portal</Link><Link href="/auth/login">Teachers Portal</Link><Link href="/auth/login">Student Portal</Link></div></div></div>
  <header className="sticky top-0 z-20 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-4"><Link href="/" className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-full border-2 border-emerald-900 text-xl">ﷲ</div><div><div className="font-serif text-xl font-black tracking-wide text-[#064e3b]">{settings.school_name?.value??'AL HUDA'}</div><div className="text-[10px] font-semibold tracking-widest text-slate-600">QURAN MEMORIZATION SCHOOL</div></div></Link><nav className="hidden items-center gap-6 lg:flex">{nav.map((x:any)=><Link href={x.href} key={x.label} className="text-sm font-semibold hover:text-emerald-700">{x.label}</Link>)}</nav><Link href="/auth/login" className="btn bg-[#064e3b] text-white">Parent / Student Portal</Link><Link href="/admissions" className="btn bg-amber-500 text-slate-950">Apply Now</Link></div></header>
  {m.hero?.visible!==false&&<section className="relative overflow-hidden bg-[#062d2a] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(251,191,36,.35),transparent_30%),linear-gradient(115deg,#062d2a,#0f766e)]"/>{hero.hero_image&&<img src={hero.hero_image} alt="School" className="absolute inset-0 h-full w-full object-cover opacity-55"/>}<div className="relative mx-auto grid min-h-[430px] max-w-7xl items-center gap-10 px-6 py-16 md:grid-cols-[1.1fr_.9fr]"><div><div className="text-sm font-bold tracking-[.25em] text-amber-300">{hero.eyebrow}</div><h1 className="mt-5 whitespace-pre-line font-serif text-4xl font-black leading-tight md:text-6xl">{hero.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-emerald-50">{hero.subtitle}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={hero.primary_href??'/admissions'} className="btn bg-emerald-700 text-white">{hero.primary_cta??'Apply for Admission'} →</Link><Link href={hero.secondary_href??'/about'} className="btn bg-white text-[#064e3b]">{hero.secondary_cta??'Learn More'} →</Link></div></div><div className="rounded-[2rem] border border-white/20 bg-black/10 p-8 text-center backdrop-blur-sm"><div className="text-6xl">ﷲ</div><p className="mt-5 font-serif text-2xl font-bold">{hero.quote}</p><div className="mt-3 text-sm text-amber-200">— {hero.quote_source}</div></div></div></section>}
  {m.features?.visible!==false&&<section className="mx-auto -mt-7 max-w-7xl px-5 relative z-10"><div className="grid gap-4 md:grid-cols-3 lg:grid-cols-6">{features.map((x:any,i:number)=><div className="rounded-2xl border bg-white p-5 text-center shadow-sm" key={i}><div className="text-2xl text-emerald-700">✦</div><h3 className="mt-3 font-bold">{x.title}</h3><p className="mt-2 text-xs leading-5 text-slate-600">{x.text}</p></div>)}</div></section>}
  {m.about?.visible!==false&&<section className="mx-auto max-w-7xl px-5 py-14"><div className="grid gap-8 lg:grid-cols-[1.05fr_.95fr]"><div><div className="text-xs font-bold uppercase tracking-[.22em] text-emerald-700">{settings.school_name?.value??''}</div><h2 className="mt-2 font-serif text-3xl font-black text-[#064e3b]">{about.title}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-600">{about.text}</p><Link href={about.cta_href??'/about'} className="btn mt-5 border border-emerald-700 text-emerald-800">{about.cta??'More About Us'} →</Link></div><div className="min-h-64 overflow-hidden rounded-3xl bg-gradient-to-br from-emerald-950 to-amber-500">{about.image&&<img src={about.image} alt="About school" className="h-full w-full object-cover"/>}</div></div></section>}
  {m.stats?.visible!==false&&<section className="mx-auto max-w-7xl px-5"><div className="grid overflow-hidden rounded-2xl bg-[#064e3b] text-white md:grid-cols-5">{stats.map((x:any,i:number)=><div key={i} className="border-b border-white/10 p-5 text-center md:border-b-0 md:border-r last:border-r-0"><div className="text-3xl font-black text-amber-300">{x.value}</div><div className="mt-1 text-xs">{x.label}</div></div>)}</div></section>}
  {m.programme?.visible!==false&&<section className="mx-auto max-w-7xl px-5 py-14"><div className="grid gap-4 lg:grid-cols-4">{(programme.items??[]).map((x:any,i:number)=><div key={i} className="card p-5"><h3 className="font-bold text-emerald-900">{x.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{x.text}</p></div>)}<div className="rounded-2xl bg-emerald-950 p-6 text-white"><div className="text-sm font-bold text-amber-300">{programme.admission_title}</div><p className="mt-2 text-sm text-emerald-100">{programme.admission_text}</p><Link href="/admissions" className="btn mt-4 bg-amber-500 text-slate-950">{programme.admission_cta} →</Link></div></div></section>}
  {m.values?.visible!==false&&<section className="bg-emerald-950 py-5 text-white"><div className="mx-auto flex max-w-7xl flex-wrap justify-center gap-x-12 gap-y-3 px-5">{values.map((x:any)=><span className="font-semibold" key={x}>✦ {x}</span>)}</div></section>}
  {m.campuses?.visible!==false&&<section className="mx-auto max-w-7xl px-5 py-14"><div className="grid gap-6 md:grid-cols-2">{campuses.map((x:any,i:number)=><article className="overflow-hidden rounded-2xl border" key={i}><div className="h-48 bg-gradient-to-br from-slate-200 to-emerald-100">{x.image&&<img src={x.image} alt={x.title} className="h-full w-full object-cover"/>}</div><div className="p-5"><h3 className="font-bold">{x.title}</h3><p className="mt-2 text-sm text-slate-600">{x.text}</p></div></article>)}</div></section>}
  {m.news?.visible!==false&&<section className="bg-[#f7f5ef] py-14"><div className="mx-auto max-w-7xl px-5"><div className="flex items-end justify-between"><div><div className="text-xs font-bold uppercase tracking-[.22em] text-emerald-700">News & Events</div><h2 className="mt-2 font-serif text-3xl font-black text-[#064e3b]">Latest News & Events</h2></div><Link href="/news" className="text-sm font-bold text-emerald-700">View All News →</Link></div><div className="mt-7 grid gap-5 md:grid-cols-3">{news.map((x:any,i:number)=><article className="overflow-hidden rounded-2xl border bg-white" key={i}><div className="h-32 bg-gradient-to-br from-emerald-900 to-amber-500">{x.image&&<img src={x.image} alt={x.title} className="h-full w-full object-cover"/>}</div><div className="p-5"><div className="text-xs text-slate-400">{x.date}</div><h3 className="mt-1 font-bold">{x.title}</h3><p className="mt-2 text-sm text-slate-600">{x.text}</p></div></article>)}</div></div></section>}
  {team.length>0&&<section className="mx-auto max-w-7xl px-5 py-14"><div className="text-xs font-bold uppercase tracking-[.22em] text-emerald-700">Leadership & Staff</div><h2 className="mt-2 font-serif text-3xl font-black text-[#064e3b]">Our Team</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{team.map((t:any)=><article className="card overflow-hidden" key={t.id}><div className="h-44 bg-gradient-to-br from-emerald-950 to-amber-500">{t.photo_url&&<img src={t.photo_url} alt={t.full_name} className="h-full w-full object-cover"/>}</div><div className="p-5"><div className="text-xs uppercase text-slate-400">{t.category}</div><h3 className="mt-1 font-black">{t.full_name}</h3><div className="text-sm font-semibold text-emerald-800">{t.role_title}</div><p className="mt-2 text-sm text-slate-600">{t.brief_bio}</p></div></article>)}</div></section>}
  {alumni.length>0&&<section className="bg-[#f7f5ef] py-14"><div className="mx-auto max-w-7xl px-5"><div className="text-xs font-bold uppercase tracking-[.22em] text-emerald-700">Alumni</div><h2 className="mt-2 font-serif text-3xl font-black text-[#064e3b]">Honouring Our Huffaz</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{alumni.slice(0,6).map((a:any)=><article className="card p-5" key={a.id}><span className="pill bg-emerald-50 text-emerald-700">{a.cohort_name}</span><h3 className="mt-3 font-black">{a.full_name}</h3><p className="mt-2 text-sm text-slate-600">{a.brief_bio}</p></article>)}</div></div></section>}
  <footer className="bg-[#053c2f] py-12 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 md:grid-cols-3"><div><div className="font-serif text-2xl font-black">{settings.school_name?.value??'AL HUDA'}</div><p className="mt-3 text-sm text-emerald-100">{footer.tagline}</p></div><div><h3 className="font-bold">Quick Links</h3><div className="mt-3 grid gap-2 text-sm text-emerald-100">{nav.slice(0,6).map((x:any)=><Link href={x.href} key={x.label}>{x.label}</Link>)}</div></div><div><h3 className="font-bold">Contact Us</h3><div className="mt-3 text-sm text-emerald-100">{contact.address}<br/>{contact.phone}<br/>{contact.email}</div></div></div></footer>
 </main>
}
