'use client';
import Link from 'next/link';
import AdminShell from '@/components/AdminShell';
import { loadEvaluations, loadStudents, loadStaffProfiles, loadClasses } from '@/lib/live-store';
import { loadFinanceSummary } from '@/lib/admin-management-store';
import { useEffect, useMemo, useState } from 'react';
const Stat=({label,value,sub,href}:{label:string,value:string,sub:string,href?:string})=><div className="card p-5">{href?<Link href={href} className="text-sm text-slate-500 hover:text-emerald-700">{label}</Link>:<div className="text-sm text-slate-500">{label}</div>}<div className="mt-2 text-3xl font-black">{value}</div><div className="mt-1 text-xs text-slate-500">{sub}</div></div>;
export default function Admin(){
 const [students,setStudents]=useState<any[]>([]),[evaluations,setEvaluations]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[finance,setFinance]=useState<any>({fees:[],payments:[]});
 useEffect(()=>{Promise.all([loadStudents(),loadEvaluations(),loadStaffProfiles(),loadClasses(),loadFinanceSummary()]).then(([s,e,st,c,f])=>{setStudents(s);setEvaluations(e);setStaff(st);setClasses(c);setFinance(f)})},[]);
 const pending=evaluations.filter(e=>e.status==='Pending Approval').length; const expected=finance.fees.reduce((n:number,x:any)=>n+Number(x.amount_due||0),0); const collected=finance.fees.reduce((n:number,x:any)=>n+Number(x.amount_paid||0),0); const attendance=students.length?Math.round(students.reduce((n,s)=>n+Number(s.attendance||0),0)/students.length):0; const activeStaff=staff.filter(s=>['active',undefined].includes(s.employment_status)).length; const distribution=useMemo(()=>Object.entries(students.reduce((m:any,s:any)=>{const k=s.className??'Unassigned';m[k]=(m[k]??0)+1;return m},{})).sort((a:any,b:any)=>b[1]-a[1]),[students]);
 return <AdminShell title="Admin Dashboard"><div className="space-y-6">
  <div className="rounded-3xl bg-gradient-to-r from-slate-950 to-emerald-950 p-6 text-white md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="text-xs font-bold uppercase tracking-[.22em] text-emerald-300">AMQM Control Center</div><h2 className="mt-2 text-3xl font-black">School operations at a glance</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Manage students, staff, classes, programmes, fees, Quran evaluations and the public website from the administrator workspace.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Link href="/students" className="rounded-xl bg-white/10 px-4 py-3 text-center text-xs font-bold hover:bg-white/15">Students</Link><Link href="/cms" className="rounded-xl bg-white/10 px-4 py-3 text-center text-xs font-bold hover:bg-white/15">Website CMS</Link><Link href="/programs" className="rounded-xl bg-white/10 px-4 py-3 text-center text-xs font-bold hover:bg-white/15">Programmes</Link><Link href="/fees" className="rounded-xl bg-white/10 px-4 py-3 text-center text-xs font-bold hover:bg-white/15">Finance</Link></div></div></div>
  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Stat label="Students" value={String(students.length)} sub={`${students.filter(s=>s.section==='Day').length} Day · ${students.filter(s=>s.section==='Boarding').length} Boarding`} href="/students"/><Stat label="Active staff" value={String(activeStaff)} sub={`${staff.filter(s=>s.role==='teacher').length} teachers`} href="/cms"/><Stat label="Classes" value={String(classes.filter(c=>c.active).length)} sub="Combined Day + Boarding classes" href="/classes"/><Stat label="Attendance" value={`${attendance}%`} sub="Average from recorded attendance" href="/attendance"/></div>
  <div className="grid gap-4 md:grid-cols-3"><Stat label="Fees expected" value={`RWF ${expected.toLocaleString()}`} sub="Current student fee allocations" href="/fees"/><Stat label="Collected" value={`RWF ${collected.toLocaleString()}`} sub="Allocated payments" href="/fees"/><Stat label="Outstanding" value={`RWF ${Math.max(0,expected-collected).toLocaleString()}`} sub="Needs finance follow-up" href="/fees"/></div>
  <div className="grid gap-5 lg:grid-cols-[1.4fr_.8fr]">
   <div className="card p-5"><div className="flex items-center justify-between"><div><h2 className="font-black">Evaluation workflow</h2><p className="text-xs text-slate-500">Teacher submissions awaiting administrator action</p></div><Link className="btn btn-primary" href="/evaluations">Review all</Link></div><div className="mt-4 space-y-3">{evaluations.slice(0,8).map((e:any)=><div className="flex items-center justify-between rounded-xl border p-3" key={e.id}><div><div className="font-semibold">{e.student}</div><div className="text-xs text-slate-500">Evaluation {e.number} · {e.status}</div></div><span className="pill bg-slate-100">{e.status}</span></div>)}{!evaluations.length&&<div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No evaluations have been submitted yet.</div>}</div></div>
   <div className="card p-5"><h2 className="font-black">Administrator actions</h2><div className="mt-4 space-y-2">{[['/cms','Manage school identity, homepage, media & staff'],['/students','Create and manage students'],['/classes','Create classes and assign teachers'],['/programs','Set programmes, years & terms'],['/fees','Set Day/Boarding fees & record payments'],['/admissions','Review applications'],['/reports','Review report cards']].map(([href,l])=><Link href={href} className="block rounded-xl border p-3 text-sm font-semibold hover:bg-slate-50" key={href}>{l}<span className="float-right">→</span></Link>)}</div></div>
  </div>
  <div className="grid gap-5 lg:grid-cols-2"><div className="card p-5"><h2 className="font-black">Students by class</h2><div className="mt-4 space-y-2">{distribution.map(([name,count]:any)=><div className="flex items-center justify-between rounded-xl bg-slate-50 p-3" key={name}><span className="font-semibold">{name}</span><span className="pill bg-white">{count}</span></div>)}{!distribution.length&&<p className="text-sm text-slate-500">No students yet.</p>}</div></div><div className="card p-5"><h2 className="font-black">Staff by role</h2><div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(staff.reduce((m:any,s:any)=>{m[s.role]=(m[s.role]||0)+1;return m},{})).map(([role,count]:any)=><div className="rounded-xl border p-3" key={role}><div className="text-xs uppercase text-slate-400">{role}</div><div className="mt-1 text-2xl font-black">{count}</div></div>)}</div></div></div>
  <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Configuration reminder:</b> use <Link className="font-bold underline" href="/cms">Website CMS</Link> for school identity/logo/media and staff, <Link className="font-bold underline" href="/programs">Program & Terms</Link> for academic structure, and <Link className="font-bold underline" href="/fees">Finance & Fees</Link> for Day/Boarding term fees and payments.</div>
 </div></AdminShell>
}
