'use client';
import AdminShell from '@/components/AdminShell';
import SectionBadge from '@/components/SectionBadge';
import {loadTeacherDirectory,loadTeacherEvaluations,recordTeacherAttendance,updateOwnProfile,uploadProfileImage,getCurrentProfile} from '@/lib/live-store';
import {useEffect,useMemo,useState} from 'react';

export default function TeacherDashboard(){
 const [students,setStudents]=useState<any[]>([]),[evaluations,setEvaluations]=useState<any[]>([]),[me,setMe]=useState<any>(null),[selected,setSelected]=useState<any|null>(null),[profileOpen,setProfileOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const refresh=async()=>{const [s,e]=await Promise.all([loadTeacherDirectory(),loadTeacherEvaluations()]);setStudents(s);setEvaluations(e)};
 useEffect(()=>{refresh();getCurrentProfile().then(setMe)},[]);
 const attendanceToday=useMemo(()=>students.length?0:0,[students]);
 async function saveProfile(){if(!me)return;setBusy(true);try{await updateOwnProfile({phone:me.phone||null,avatar_url:me.avatar_url||null});setMessage('Your profile has been updated.');setProfileOpen(false)}catch(e:any){setMessage(e?.message||'Unable to update profile')}finally{setBusy(false)}}
 async function uploadPhoto(file:File|null){if(!file)return;setBusy(true);try{const url=await uploadProfileImage(file,'staff');setMe((x:any)=>({...x,avatar_url:url}));await updateOwnProfile({avatar_url:url});setMessage('Profile photo updated.');}catch(e:any){setMessage(e?.message||'Photo upload failed')}finally{setBusy(false)}}
 async function mark(studentId:string,status:any){setBusy(true);try{await recordTeacherAttendance(studentId,status);setMessage('Attendance recorded.');}catch(e:any){setMessage(e?.message||'Attendance could not be recorded')}finally{setBusy(false)}}
 return <AdminShell title="Teacher Workspace"><div className="space-y-5">
  <section className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#062d2a] via-emerald-900 to-slate-950 p-5 text-white shadow-xl md:p-7"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="text-[11px] font-bold uppercase tracking-[.24em] text-amber-300">My classroom</div><h2 className="mt-2 text-3xl font-black md:text-4xl">Your students. Your impact.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-emerald-50/80">A focused workspace for the students assigned to you. Student records are read-only; attendance and assigned evaluations are the only academic actions available here.</p></div><button onClick={()=>setProfileOpen(true)} className="flex items-center gap-3 rounded-2xl bg-white/10 p-2 pr-4 text-left backdrop-blur hover:bg-white/15"><div className="h-12 w-12 overflow-hidden rounded-full bg-white/15">{me?.avatar_url?<img src={me.avatar_url} className="h-full w-full object-cover" alt="Profile"/>:<div className="flex h-full items-center justify-center font-black">T</div>}</div><div><div className="text-sm font-bold">My profile</div><div className="text-xs text-emerald-100/70">Update phone & photo</div></div></button></div></section>
  {message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</div>}
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="card p-5"><div className="text-xs uppercase tracking-wider text-slate-400">Assigned students</div><div className="mt-2 text-3xl font-black">{students.length}</div></div><div className="card p-5"><div className="text-xs uppercase tracking-wider text-slate-400">Day</div><div className="mt-2 text-3xl font-black">{students.filter(s=>s.section==='Day').length}</div></div><div className="card p-5"><div className="text-xs uppercase tracking-wider text-slate-400">Boarding</div><div className="mt-2 text-3xl font-black">{students.filter(s=>s.section==='Boarding').length}</div></div><div className="card p-5"><div className="text-xs uppercase tracking-wider text-slate-400">Pushed evaluations</div><div className="mt-2 text-3xl font-black">{evaluations.length}</div></div></div>
  <section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black">My students</h2><p className="text-xs text-slate-500">Only students explicitly assigned to your account are shown.</p></div><div className="rounded-xl bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800">Read-only student records</div></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{students.map(s=><article key={s.id} className="rounded-2xl border p-4 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start gap-3"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-2xl bg-slate-100">{s.photoUrl?<img src={s.photoUrl} alt={s.name} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-lg font-black text-slate-400">{s.name?.charAt(0)}</div>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-black">{s.name}</h3><SectionBadge section={s.section}/></div><div className="mt-1 text-xs text-slate-500">{s.admissionNo} · {s.year} · {s.className||'No class'}</div></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Starting</span><br/><b>Surah {s.start?.surah??'—'}:{s.start?.ayah??'—'}</b></div><div className="rounded-xl bg-emerald-50 p-3"><span className="text-emerald-600">Current</span><br/><b>Surah {s.current?.surah??'—'}:{s.current?.ayah??'—'}</b></div></div><div className="mt-3 flex gap-2"><button className="btn flex-1 bg-slate-100" onClick={()=>setSelected(s)}>Full profile</button><select disabled={busy} onChange={e=>{if(e.target.value)mark(s.id,e.target.value)}} defaultValue="" className="input flex-1"><option value="">Attendance</option><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="excused">Excused</option></select></div></article>)}{!students.length&&<div className="col-span-full rounded-2xl bg-slate-50 p-10 text-center text-sm text-slate-500">No students are currently assigned to your account.</div>}</div></section>
  {evaluations.length>0&&<section className="card p-5"><div className="flex items-center justify-between"><div><h2 className="font-black">Evaluations from Admin</h2><p className="text-xs text-slate-500">Only evaluations deliberately pushed to you appear here.</p></div><span className="pill bg-amber-50 text-amber-700">Admin controlled</span></div><div className="mt-4 space-y-2">{evaluations.map((e:any)=><div key={e.id} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div><b>{e.students?.full_name}</b><div className="text-xs text-slate-500">Evaluation {e.evaluation_number} · {String(e.status).replace('_',' ')}</div></div><span className="pill bg-slate-100">Score {e.score??'—'}</span></div></div>)}</div></section>}
  {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/50 p-0 backdrop-blur-sm sm:items-center sm:p-5" onClick={()=>setSelected(null)}><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-t-3xl bg-white p-5 sm:rounded-3xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><div className="text-xs uppercase tracking-wider text-emerald-700">Student profile</div><h2 className="mt-1 text-2xl font-black">{selected.name}</h2></div><button className="btn bg-slate-100" onClick={()=>setSelected(null)}>Close</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><b>Admission</b><p className="mt-1 text-sm">{selected.admissionNo}</p></div><div className="rounded-xl bg-slate-50 p-4"><b>Section</b><p className="mt-1 text-sm">{selected.section}</p></div><div className="rounded-xl bg-slate-50 p-4"><b>Date of birth</b><p className="mt-1 text-sm">{selected.dateOfBirth||'—'}</p></div><div className="rounded-xl bg-slate-50 p-4"><b>Gender</b><p className="mt-1 text-sm">{selected.gender||'—'}</p></div><div className="rounded-xl bg-emerald-50 p-4"><b>Qur'an starting point</b><p className="mt-1 text-sm">Surah {selected.start?.surah??'—'} : Ayah {selected.start?.ayah??'—'}</p></div><div className="rounded-xl bg-emerald-50 p-4"><b>Current position</b><p className="mt-1 text-sm">Surah {selected.current?.surah??'—'} : Ayah {selected.current?.ayah??'—'}</p></div></div><div className="mt-5 rounded-2xl border p-4"><div className="text-xs uppercase tracking-wider text-slate-400">Connected parent / guardian</div><div className="mt-2 font-black">{selected.parent?.name||'Not connected'}</div><div className="mt-1 text-sm text-slate-600">{selected.parent?.relationship||'—'} · {selected.parent?.phone||'No phone'}</div></div></div></div>}
  {profileOpen&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/50 p-0 sm:items-center sm:p-5" onClick={()=>setProfileOpen(false)}><div className="w-full max-w-md rounded-t-3xl bg-white p-5 sm:rounded-3xl" onClick={e=>e.stopPropagation()}><div className="text-xs uppercase tracking-wider text-emerald-700">My profile</div><h2 className="mt-1 text-2xl font-black">Teacher account</h2><div className="mt-5 flex items-center gap-4"><div className="h-20 w-20 overflow-hidden rounded-2xl bg-slate-100">{me?.avatar_url?<img src={me.avatar_url} className="h-full w-full object-cover" alt="Profile"/>:<div className="flex h-full items-center justify-center font-black text-slate-400">T</div>}</div><label className="btn bg-slate-100">Change photo<input hidden type="file" accept="image/*" onChange={e=>uploadPhoto(e.target.files?.[0]||null)}/></label></div><label className="mt-5 block text-sm font-semibold">Phone<input className="input mt-1" value={me?.phone||''} onChange={e=>setMe((x:any)=>({...x,phone:e.target.value}))}/></label><div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-500">Your staff ID and role are controlled by Admin and cannot be changed here.</div><div className="mt-5 flex gap-2"><button className="btn flex-1 bg-slate-100" onClick={()=>setProfileOpen(false)}>Cancel</button><button className="btn btn-primary flex-1" disabled={busy} onClick={saveProfile}>Save changes</button></div></div></div>}
 </div></AdminShell>
}
