'use client';
import {Student,studentStats} from '@/lib/data';
import {juzForPosition} from '@/lib/quran';
export default function QuranProgress({student,compact=false}:{student:Student;compact?:boolean}){
 const s=studentStats(student); const pct=Math.min(100,Math.max(0,s.percent)); const circumference=2*Math.PI*48; const dash=circumference*(pct/100);
 return <div className="card overflow-hidden p-0 shadow-sm"><div className="bg-gradient-to-br from-[#063b34] via-emerald-900 to-[#0a5d51] p-5 text-white md:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="relative mx-auto shrink-0 sm:mx-0"><svg width="122" height="122" viewBox="0 0 122 122" className="-rotate-90"><circle cx="61" cy="61" r="48" fill="none" stroke="rgba(255,255,255,.12)" strokeWidth="10"/><circle cx="61" cy="61" r="48" fill="none" stroke="#e7bb55" strokeWidth="10" strokeLinecap="round" strokeDasharray={`${dash} ${circumference-dash}`} className="transition-all duration-700"/></svg><div className="absolute inset-0 grid place-items-center text-center"><div><div className="text-2xl font-black">{pct.toFixed(1)}%</div><div className="text-[9px] uppercase tracking-wider text-emerald-100/70">Qur'an complete</div></div></div></div><div className="min-w-0 flex-1"><div className="text-[11px] font-black uppercase tracking-[.2em] text-amber-300">Hifz journey</div><h3 className="mt-1 text-2xl font-black">{s.currentLabel}</h3><p className="mt-1 text-sm text-emerald-50/80">Started at {s.startLabel} · {student.direction}</p><div className="mt-4 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-emerald-300 via-teal-300 to-amber-300 transition-all duration-700" style={{width:`${pct}%`}}/></div><div className="mt-2 flex flex-wrap justify-between gap-2 text-xs font-semibold text-emerald-100/70"><span>{pct.toFixed(1)}% of the Qur'an · {s.hizbs.toFixed(1)} / 60 Hizb</span><span>{s.remaining.ayahs.toLocaleString()} ayahs left</span></div></div></div></div>
 <div className="p-5 md:p-6"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Ayahs memorized" value={s.ayahs.toLocaleString()}/><Stat label="Pages memorized" value={s.pages.toLocaleString()}/><Stat label="Hizb memorized" value={`${s.hizbs.toFixed(1)} / 60`}/><Stat label="Mushaf page" value={`${s.currentPage} / 604`}/></div><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Ayahs remaining" value={s.remaining.ayahs.toLocaleString()} tone="amber"/><Stat label="Pages remaining" value={s.remaining.pages.toLocaleString()} tone="amber"/><Stat label="Hizb remaining" value={s.remaining.hizbs.toLocaleString()} tone="amber"/><Stat label="Current Juz / Hizb" value={`${juzForPosition(student.current)} / ${s.currentHizb}`}/></div>{!compact&&<div className="mt-4 rounded-2xl border border-emerald-100 bg-emerald-50 p-4"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-emerald-950">Official progress</b><p className="text-xs text-emerald-800/70">Only Admin-approved evaluations move this position.</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-emerald-700">{pct>=100?'Qur’an Completed':'In Progress'}</span></div></div>}</div></div>
}
function Stat({label,value,tone}:{label:string;value:string;tone?:'amber'}){return <div className={`rounded-2xl border p-3 ${tone==='amber'?'border-amber-100 bg-amber-50':'bg-slate-50'}`}><div className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</div><div className={`mt-1 text-lg font-black ${tone==='amber'?'text-amber-900':'text-slate-900'}`}>{value}</div></div>}
