'use client';

import AdminShell from '@/components/AdminShell';
import {loadAdmissionApplications,updateAdmissionApplication,enrollAdmissionApplication,loadClasses,scheduleAdmissionScreening,saveAdmissionScreening} from '@/lib/live-store';
import {loadCMSSettings,saveCMSSetting} from '@/lib/cms-live-store';
import {useEffect,useMemo,useState} from 'react';

export default function AdmissionsManage(){
 const [items,setItems]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[settings,setSettings]=useState<any>({}),[selected,setSelected]=useState<any|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [scheduleAt,setScheduleAt]=useState('');
 const refresh=async()=>{const [a,c,s]=await Promise.all([loadAdmissionApplications(),loadClasses(),loadCMSSettings()]);setItems(a);setClasses(c);setSettings(s)};
 useEffect(()=>{refresh()},[]);
 const portal=settings.admission_portal||{};
 const payment=settings.school_payment||{};
 const virtualCount=useMemo(()=>items.filter(a=>a.screening_mode==='virtual').length,[items]);

 async function savePortal(){
   setBusy(true);try{await saveCMSSetting('admission_portal',{enabled:!!portal.enabled,opening_date:portal.opening_date||null,closing_date:portal.closing_date||null,screening_date:portal.screening_date||null});setMessage('Admission portal schedule saved.');await refresh()}catch(e:any){setMessage(e?.message||'Unable to save')}finally{setBusy(false)}
 }
 async function verify(a:any){setBusy(true);try{await updateAdmissionApplication(a.id,{payment_status:'verified',payment_reference:a.payment_reference||null,status:'payment_verified'});setMessage(a.application_no+' payment verified.');await refresh()}catch(e:any){setMessage(e?.message||'Unable to verify')}finally{setBusy(false)}}
 async function schedule(a:any){
   if(!scheduleAt)return;
   setBusy(true);try{const r=await scheduleAdmissionScreening(a.id,scheduleAt,'');setMessage(a.application_no+' screening scheduled as '+r.screening_mode+'.');setScheduleAt('');await refresh();setSelected(null)}catch(e:any){setMessage(e?.message||'Unable to schedule screening')}finally{setBusy(false)}
 }
 async function outcome(a:any,outcome:'successful'|'unsuccessful'|'further_assessment'){
   setBusy(true);try{await saveAdmissionScreening(a.id,outcome,a.screening_score?Number(a.screening_score):null,a.screening_notes||'');setMessage(a.application_no+' marked '+outcome.replace('_',' ')+'.');await refresh();setSelected(null)}catch(e:any){setMessage(e?.message||'Unable to save screening outcome')}finally{setBusy(false)}
 }
 async function enroll(a:any){setBusy(true);try{const r=await enrollAdmissionApplication(a.id,a.class_id||null,a.starting_surah?Number(a.starting_surah):null,a.starting_ayah?Number(a.starting_ayah):null,a.screening_score?Number(a.screening_score):null,a.screening_notes||'');setMessage('Enrolled '+r.admission_no+'. Quran starting position preserved.');await refresh()}catch(e:any){setMessage(e?.message||'Unable to enroll')}finally{setBusy(false)}}

 return <AdminShell title="Admissions Management"><div className="space-y-6">
  <section className="rounded-3xl bg-gradient-to-br from-slate-950 to-emerald-950 p-6 text-white"><div><div className="text-xs font-bold uppercase tracking-[.22em] text-amber-300">Admissions lifecycle</div><h2 className="mt-2 text-3xl font-black">Application → Screening → Decision → Class → Quran start.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-50/75">Adamawa applicants are scheduled for physical screening. Applicants outside Adamawa are scheduled into AMQM's own secure browser video room with a unique link.</p></div></section>
  {message&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</div>}
  <section className="grid gap-4 lg:grid-cols-3">
   <div className="card p-5 lg:col-span-2"><h2 className="font-black">Admission portal</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-sm font-semibold sm:col-span-2"><input type="checkbox" checked={!!portal.enabled} onChange={e=>setSettings((x:any)=>({...x,admission_portal:{...portal,enabled:e.target.checked}}))}/> Portal open for applications</label><label className="text-sm font-semibold">Opening date<input className="input mt-1" type="date" value={portal.opening_date||''} onChange={e=>setSettings((x:any)=>({...x,admission_portal:{...portal,opening_date:e.target.value}}))}/></label><label className="text-sm font-semibold">Closing date<input className="input mt-1" type="date" value={portal.closing_date||''} onChange={e=>setSettings((x:any)=>({...x,admission_portal:{...portal,closing_date:e.target.value}}))}/></label></div><button disabled={busy} onClick={savePortal} className="btn btn-primary mt-4">Save admissions settings</button></div>
   <div className="card p-5"><div className="text-xs font-black uppercase tracking-widest text-emerald-700">Virtual screenings</div><div className="mt-2 text-4xl font-black">{virtualCount}</div><p className="mt-1 text-xs text-slate-500">Applications from outside Adamawa requiring an online interview.</p></div>
  </section>
  <section className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-black">Application queue</h2><p className="text-xs text-slate-500">Submitted → payment verified → screening scheduled → successful / unsuccessful / further assessment → enrolled.</p></div><div className="divide-y">
   {items.map(a=><div key={a.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{a.applicant_name}</h3><span className="pill bg-slate-100">{a.status}</span><span className="pill bg-amber-50 text-amber-800">{a.payment_status}</span><span className="pill bg-emerald-50 text-emerald-800">{a.screening_mode||'—'}</span></div><div className="mt-1 text-xs text-slate-500">{a.application_no} · {a.state||'—'} · {a.lga||'—'} · {a.parent_phone}</div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><b>Quran start:</b> {a.starting_surah?'Surah '+a.starting_surah+' : Ayah '+(a.starting_ayah||1):'Assign after screening'}</div><div><b>Screening:</b> {a.screening_scheduled_at?new Date(a.screening_scheduled_at).toLocaleString():a.screening_outcome||'Not scheduled'}</div></div>{a.screening_mode==='virtual'&&a.screening_token&&<div className="mt-2 break-all text-xs text-emerald-700">Applicant link: /admissions/screening/{a.screening_token}</div>}</div><div className="flex flex-wrap gap-2 lg:max-w-sm lg:justify-end"><button className="btn bg-slate-100" onClick={()=>setSelected(a)}>Details</button>{a.payment_status!=='verified'&&<button className="btn btn-green" onClick={()=>verify(a)}>Verify payment</button>}{a.payment_status==='verified'&&a.screening_outcome!=='successful'&&a.screening_outcome!=='unsuccessful'&&<button className="btn bg-amber-100 text-amber-900" onClick={()=>{setSelected(a);setScheduleAt(a.screening_scheduled_at?new Date(a.screening_scheduled_at).toISOString().slice(0,16):'')}}>Schedule screening</button>}{a.screening_outcome==='successful'&&a.status==='accepted'&&<button className="btn btn-primary" onClick={()=>enroll(a)}>Enroll student</button>}{a.screening_mode==='virtual'&&a.screening_token&&<a className="btn bg-emerald-100 text-emerald-900" target="_blank" rel="noreferrer" href={'/admissions/screening/'+a.screening_token+'?role=interviewer'}>Open video room</a>}</div></div></div>)}
   {!items.length&&<div className="p-10 text-center text-sm text-slate-500">No applications yet.</div>}
  </div></section>
  {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/50 sm:items-center sm:p-5" onClick={()=>setSelected(null)}><div className="max-h-[92vh] w-full max-w-3xl overflow-auto rounded-t-3xl bg-white p-6 sm:rounded-3xl" onClick={e=>e.stopPropagation()}>
   <div className="flex justify-between"><div><div className="text-xs uppercase tracking-wider text-emerald-700">Application {selected.application_no}</div><h2 className="mt-1 text-2xl font-black">{selected.applicant_name}</h2></div><button className="btn bg-slate-100" onClick={()=>setSelected(null)}>Close</button></div>
   <div className="mt-5 grid gap-3 sm:grid-cols-2">{[['Date of birth',selected.date_of_birth],['Gender',selected.gender],['Parent',selected.parent_name],['Parent phone',selected.parent_phone],['Guardian',selected.guardian_name],['Guardian phone',selected.guardian_phone],['Email',selected.guardian_email],['Address',(selected.address||'—')+', '+(selected.lga||'')+', '+(selected.state||'')],['Quran level',selected.quran_level],['Screening mode',selected.screening_mode],['Screening time',selected.screening_scheduled_at?new Date(selected.screening_scheduled_at).toLocaleString():'—'],['Outcome',selected.screening_outcome||'Pending']].map(([k,v])=><div className="rounded-xl bg-slate-50 p-3" key={k as string}><div className="text-xs text-slate-400">{k}</div><div className="mt-1 text-sm font-semibold">{v||'—'}</div></div>)}</div>
   <div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-black text-slate-600">Class after successful screening<select className="input mt-1 w-full" value={selected.class_id||''} onChange={e=>setSelected((x:any)=>({...x,class_id:e.target.value}))}><option value="">Assign class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs font-black text-slate-600">Screening time<input className="input mt-1 w-full" type="datetime-local" value={scheduleAt} onChange={e=>setScheduleAt(e.target.value)}/></label><input className="input" type="number" placeholder="Screening score" value={selected.screening_score||''} onChange={e=>setSelected((x:any)=>({...x,screening_score:e.target.value}))}/><textarea className="input sm:col-span-2" placeholder="Screening notes / assessment" value={selected.screening_notes||''} onChange={e=>setSelected((x:any)=>({...x,screening_notes:e.target.value}))}/></div>
   <div className="mt-4 flex flex-wrap gap-2"><button disabled={busy||selected.payment_status!=='verified'} className="btn bg-amber-100 text-amber-900" onClick={()=>schedule(selected)}>Schedule {selected.screening_mode==='virtual'?'video':'physical'} screening</button>{selected.screening_mode==='virtual'&&selected.screening_token&&<a className="btn bg-emerald-100 text-emerald-900" target="_blank" rel="noreferrer" href={'/admissions/screening/'+selected.screening_token+'?role=interviewer'}>Open interview room</a>}</div>
   <div className="mt-6 border-t pt-5"><div className="text-xs font-black uppercase tracking-widest text-slate-500">Decision</div><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} className="btn btn-green" onClick={()=>outcome(selected,'successful')}>Successful</button><button disabled={busy} className="btn bg-rose-100 text-rose-900" onClick={()=>outcome(selected,'unsuccessful')}>Unsuccessful</button><button disabled={busy} className="btn bg-amber-100 text-amber-900" onClick={()=>outcome(selected,'further_assessment')}>Further Assessment Required</button></div></div>
   <div className="mt-6 border-t pt-5"><div className="text-xs font-black uppercase tracking-widest text-slate-500">After successful screening</div><p className="mt-2 text-sm text-slate-500">Assign the class and Quran starting Surah/Ayah, then enroll. The student's Quran journey starts from that position and continues across future school years.</p></div>
  </div></div>}
 </div></AdminShell>
}