'use client';
import AdminShell from '@/components/AdminShell';
import QuranProgress from '@/components/QuranProgress';
import SectionBadge from '@/components/SectionBadge';
import { Student } from '@/lib/data';
import { loadClasses, loadStudents, updateStudentClass, updateStudentSection, type LiveClass } from '@/lib/live-store';
import { useEffect, useMemo, useState } from 'react';

export default function Students(){
 const [all,setAll]=useState<Student[]>([]),[classes,setClasses]=useState<LiveClass[]>([]),[q,setQ]=useState(''),[section,setSection]=useState('All');
 const [selected,setSelected]=useState<Student|null>(null),[edit,setEdit]=useState<Student|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 async function refresh(){const [students,cls]=await Promise.all([loadStudents(),loadClasses()]);setAll(students);setClasses(cls)}
 useEffect(()=>{refresh()},[]);
 const filtered=useMemo(()=>all.filter(s=>(section==='All'||s.section===section)&&s.name.toLowerCase().includes(q.toLowerCase())),[all,q,section]);
 async function saveStudent(){if(!edit)return;setSaving(true);setMessage('');try{await updateStudentSection(edit.id,edit.section==='Boarding'?'boarding':'day');const cls=classes.find(c=>c.name===edit.className);await updateStudentClass(edit.id,cls?.id??null);await refresh();const fresh=(await loadStudents()).find(s=>s.id===edit.id);if(fresh)setSelected(fresh);setEdit(null);setMessage('Student section/class updated successfully.')}catch(e:any){setMessage(e?.message??'Unable to update student.')}finally{setSaving(false)}}
 return <AdminShell title="Students"><div className="card overflow-hidden"><div className="flex flex-col gap-3 border-b p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold">Student Directory</h2><p className="text-xs text-slate-500">Every student carries a visible Day/Boarding badge. Admin can change the section and class when needed.</p></div><button className="btn btn-primary" onClick={()=>alert('Student creation is handled through the authorised admissions/enrollment workflow.')}>+ Add Student</button></div><div className="flex flex-col gap-3 border-b p-4 md:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search student..." className="rounded-lg border px-3 py-2 text-sm md:w-72"/><select value={section} onChange={e=>setSection(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option>All</option><option>Day</option><option>Boarding</option></select></div>{message&&<div className="border-b bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</div>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase"><tr><th className="p-4">Student</th><th>Section</th><th>Class</th><th>Year</th><th>Memorization</th><th>Attendance</th><th>Outstanding</th><th></th></tr></thead><tbody>{filtered.map(s=><tr className="border-t" key={s.id}><td className="p-4"><b>{s.name}</b><div className="text-xs text-slate-500">{s.id} · {s.direction}</div></td><td><SectionBadge section={s.section}/></td><td>{s.className??'Unassigned'}</td><td>{s.year}</td><td>{Math.round((s.current.surah/114)*100)}% journey</td><td>{s.attendance}%</td><td className={s.fees?'font-bold text-rose-600':'text-emerald-600'}>{s.fees?'₦'+s.fees.toLocaleString():'Paid'}</td><td className="pr-4"><div className="flex gap-2"><button onClick={()=>setSelected(s)} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold">Profile</button><button onClick={()=>setEdit(s)} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Edit</button></div></td></tr>)}</tbody></table></div></div>
 {selected&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/40 p-4"><div className="mx-auto mt-8 w-full max-w-3xl rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><div className="text-xs text-slate-500">{selected.id}</div><div className="flex items-center gap-2"><h2 className="text-2xl font-black">{selected.name}</h2><SectionBadge section={selected.section}/></div><p className="text-sm text-slate-500">{selected.year} · Class: {selected.className??'Unassigned'} · Teacher: {selected.teacher}</p></div><button onClick={()=>setSelected(null)}>✕</button></div><div className="mt-5"><QuranProgress student={selected}/></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm md:grid-cols-4"><div className="rounded-xl bg-slate-50 p-3">Attendance<br/><b>{selected.attendance}%</b></div><div className="rounded-xl bg-rose-50 p-3">Fees due<br/><b>₦{selected.fees.toLocaleString()}</b></div><div className="rounded-xl bg-slate-50 p-3">Start<br/><b>{selected.start.surah}:{selected.start.ayah}</b></div><div className="rounded-xl bg-slate-50 p-3">Current<br/><b>{selected.current.surah}:{selected.current.ayah}</b></div></div><button onClick={()=>setSelected(null)} className="btn btn-primary mt-5 w-full">Close profile</button></div></div>}
 {edit&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/40 p-4"><div className="mx-auto mt-8 w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><h2 className="text-xl font-black">Edit student placement</h2><p className="text-sm text-slate-500">Admin can change the student's residential section independently of their class.</p></div><button onClick={()=>setEdit(null)}>✕</button></div><div className="mt-5 space-y-4"><div><label className="text-xs font-bold">Student</label><div className="mt-1 rounded-lg bg-slate-50 p-3 font-bold">{edit.name}</div></div><div><label className="text-xs font-bold">Section</label><select className="input mt-1 w-full" value={edit.section} onChange={e=>setEdit({...edit,section:e.target.value as 'Day'|'Boarding'})}><option>Day</option><option>Boarding</option></select></div><div><label className="text-xs font-bold">Class</label><select className="input mt-1 w-full" value={edit.className??''} onChange={e=>setEdit({...edit,className:e.target.value||null})}><option value="">Unassigned</option>{classes.filter(c=>c.active).map(c=><option key={c.id} value={c.name}>{c.name}{c.programYear?` · ${c.programYear}`:''}</option>)}</select></div><div className="rounded-xl bg-emerald-50 p-3 text-xs font-semibold text-emerald-800">This student will display a <b>{edit.section}</b> badge everywhere their name appears to authorized users.</div></div><div className="mt-6 flex justify-end gap-2"><button className="btn bg-slate-100" onClick={()=>setEdit(null)}>Cancel</button><button className="btn btn-primary" disabled={saving} onClick={saveStudent}>{saving?'Saving...':'Save changes'}</button></div></div></div>}
 </AdminShell>
}
