-- Database-backed homepage content seed. Safe to rerun.
insert into public.site_settings(key,value) values
('school_name','{"value":"AL HUDA QURAN MEMORIZATION SCHOOL"}'::jsonb),
('contact','{"phone":"+250 788 123 456","email":"info@alhuda-quran.ac.rw","address":"KG 123 St, Kicukiro, Kigali, Rwanda"}'::jsonb),
('social_links','{"facebook":"","twitter":"","instagram":"","youtube":""}'::jsonb),
('nav','{"links":[{"label":"Home","href":"/"},{"label":"About Us","href":"/about"},{"label":"Programs","href":"/programs"},{"label":"Admissions","href":"/admissions"},{"label":"Campus Life","href":"/campus-life"},{"label":"News & Events","href":"/news"},{"label":"Contact Us","href":"/contact"}]}'::jsonb)
on conflict(key) do nothing;

insert into public.homepage_sections(section_key,title,content,sort_order,visible) values
('hero','Memorizing the Book of Allah. Building a Better Ummah.','{"eyebrow":"A two-year journey with the Book of Allah","title":"Memorizing the Book of Allah\nBuilding a Better Ummah","subtitle":"A structured 2-year Quran memorization program that nurtures hearts, strengthens faith and builds a strong foundation for a life with the Quran.","hero_image":"","quote":"Indeed, it is We who sent down the Quran and indeed, We will be its guardian.","quote_source":"Al-Hijr (15:9)","primary_cta":"Apply for Admission","primary_href":"/admissions","secondary_cta":"Learn More","secondary_href":"/about"}'::jsonb,1,true),
('features','Why Al Huda','{"items":[{"title":"Quran Memorization","text":"Two-year structured program (Year 1 & Year 2)"},{"title":"Day & Boarding","text":"Quality education in a conducive environment"},{"title":"Qualified Teachers","text":"Experienced Huffaz and Islamic scholars"},{"title":"3 Evaluations Per Term","text":"Continuous assessment and improvement"},{"title":"Progress Tracking","text":"Real-time memorization progress tracking"},{"title":"Values & Character","text":"Building strong Islamic values and character"}]}'::jsonb,2,true),
('about','About Al Huda','{"title":"About Our School","text":"Al Huda Quran Memorization School is dedicated to nurturing the next generation of Huffaz through quality Quran memorization, Islamic education and character development in a safe and supportive environment.","image":"","cta":"More About Us","cta_href":"/about"}'::jsonb,3,true),
('stats','School at a glance','{"items":[{"value":"256+","label":"Students"},{"value":"24","label":"Teachers"},{"value":"2","label":"Years Program"},{"value":"3","label":"Evaluations Per Term"},{"value":"98%","label":"Parent Satisfaction"}]}'::jsonb,4,true),
('programme','Our Programme','{"items":[{"title":"Two-Year Program","text":"Year 1 & Year 2 structured Quran memorization program"},{"title":"Three Evaluations","text":"Students are evaluated 3 times each term"},{"title":"Complete Quran","text":"Memorization from An-Nas to Al-Baqarah or Al-Baqarah to An-Nas"}],"admission_title":"Admissions Open","admission_text":"Enroll your child today for a brighter Islamic future.","admission_cta":"Apply Now"}'::jsonb,5,true),
('values','Our Values','{"items":["Discipline","Excellence","Integrity","Faith","Knowledge"]}'::jsonb,6,true),
('campuses','Our Campuses','{"items":[{"title":"Day School","text":"A conducive environment for day scholars.","image":""},{"title":"Boarding School","text":"Comfortable boarding facilities for students.","image":""}]}'::jsonb,7,true),
('news','Latest News & Events','{"items":[{"title":"New Academic Year 2024/2025","text":"We welcome all students back for a new academic year.","date":"May 5, 2024","image":""},{"title":"Quran Competition","text":"Inter-class Quran memorization competition was successfully held.","date":"Apr 20, 2024","image":""},{"title":"Parent Orientation","text":"Orientation program for new parents and students.","date":"Apr 10, 2024","image":""}]}'::jsonb,8,true),
('footer','Footer','{"tagline":"Nurturing Huffaz, building character, and shaping the future.","newsletter_title":"Subscribe to Our Newsletter","newsletter_text":"Get the latest news and updates from our school."}'::jsonb,9,true)
on conflict(section_key) do update set title=excluded.title, content=excluded.content, sort_order=excluded.sort_order, visible=excluded.visible, updated_at=now();

insert into public.pages(slug,title,content,seo_title,seo_description,published) values
('about','About Us','{"intro":"Al Huda Quran Memorization School is dedicated to nurturing Huffaz through Quran memorization, Islamic education and character development.","sections":[{"title":"Our Mission","text":"Provide a safe, disciplined and supportive environment where students memorize the Quran, strengthen character and build a lifelong relationship with the Book of Allah."},{"title":"Our Approach","text":"Students follow a structured two-year programme with daily memorization, revision and three formal evaluations each term."}]}'::jsonb,'About Al Huda','Our mission, approach and values.',true),
('programs','Programs','{"intro":"A structured two-year Quran memorization programme for Day and Boarding students.","sections":[{"title":"Year 1","text":"Foundation, consistent daily memorization, revision and the first three terms of formal assessment."},{"title":"Year 2","text":"Advanced memorization, revision, final evaluations and graduation readiness."},{"title":"Direction","text":"Students may begin from An-Nas toward Al-Baqarah or from Al-Baqarah toward An-Nas. Their official direction is enforced by the evaluation workflow."}]}'::jsonb,'Quran Memorization Programmes','Two-year Quran memorization programmes.',true),
('campus-life','Campus Life','{"intro":"A safe and supportive environment for both Day and Boarding students.","sections":[{"title":"Day School","text":"Structured school-day learning, Quran memorization, revision and pastoral support."},{"title":"Boarding","text":"Residential care, supervised study, meals and a disciplined environment designed around learning and worship."}]}'::jsonb,'Campus Life','Day and Boarding campus life.',true),
('news','News & Events','{"intro":"School announcements, Quran competitions, parent events and community updates.","sections":[{"title":"Stay Connected","text":"Administrators can update news, events and announcements through the CMS without changing website code."}]}'::jsonb,'News & Events','Latest school news and events.',true),
('contact','Contact Us','{"intro":"Contact Al Huda Quran Memorization School.","sections":[{"title":"School Office","text":"Use the contact details published in the website CMS. Administrators can change the phone, email, address and social links without changing code."}]}'::jsonb,'Contact Al Huda','School contact information.',true)
on conflict(slug) do update set title=excluded.title,content=excluded.content,seo_title=excluded.seo_title,seo_description=excluded.seo_description,published=true,updated_at=now();
