-- Scan-based admission number generator.
--
-- The counter-driven helper (next_school_number) kept handing back
-- values that collided with real students, because the counter had
-- lagged behind reality after historic bulk-imports. We saw the raw
-- postgres error "Key (admission_no)=(AMQM/STU/2025/004) already
-- exists" even when the helper thought "003" was free.
--
-- Admin requested: "check the list of the entire admission numbers
-- we have for both 2025 and 2026, and decide or assigned the next
-- vacant number ... and same with student enrollments and admissions
-- too, you need to scan first".
--
-- amqm_next_vacant_student_admission_no now scans directly:
--   1. public.students.admission_no      (the live roster)
--   2. public.admissions.application_no  (pending applications; same
--                                         pattern so collisions on
--                                         future enrolment don't
--                                         repeat the number)
-- Both case-insensitively. It then returns the lowest N starting
-- from 1 whose padded form is NOT in that combined set. The counter
-- is also advanced to max(N, counter)+1 so new INSERTs via the
-- existing trigger stay consistent, but the counter is never TRUSTED
-- by this helper -- the live scan is the source of truth.
--
-- Replaces the version from migration 20261008140000. Signature
-- unchanged, so admin_update_student_profile keeps working.

create or replace function public.amqm_next_vacant_student_admission_no(
  p_year integer
) returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_year_token text := p_year::text;
  v_prefix     text := 'AMQM/STU/' || v_year_token || '/';
  v_pattern    text := '^AMQM/STU/' || v_year_token || '/(\d+)$';
  v_next       integer;
  v_candidate  text;
  v_rec        record;
  v_max_seen   integer := 0;
begin
  -- Materialise every used sequence number for this year across the
  -- two tables that mint them. We treat the lookup as case-insensitive
  -- to catch legacy "AMQM/Stu/..." rows generated by the old mixed-case
  -- helper. Both columns are indexed, so the full scan is cheap for a
  -- few hundred rows per year.
  create temporary table if not exists amqm_tmp_used_adm (n integer primary key) on commit drop;
  truncate amqm_tmp_used_adm;

  insert into amqm_tmp_used_adm (n)
  select (regexp_match(admission_no, v_pattern, 'i'))[1]::integer as n
  from public.students
  where admission_no ~* v_pattern
  on conflict do nothing;

  insert into amqm_tmp_used_adm (n)
  select (regexp_match(application_no, v_pattern, 'i'))[1]::integer as n
  from public.admissions
  where application_no ~* v_pattern
  on conflict do nothing;

  select coalesce(max(n), 0) into v_max_seen from amqm_tmp_used_adm;

  -- Find the smallest n >= 1 that is not in the used set. We prefer
  -- filling gaps over blindly going past the max so a hand-numbered
  -- old record (e.g. "045" when the row for "044" was never created)
  -- doesn't force a jump to "046".
  for v_rec in
    select gs.n
    from generate_series(1, v_max_seen + 1) as gs(n)
    where not exists (select 1 from amqm_tmp_used_adm u where u.n = gs.n)
    order by gs.n
    limit 1
  loop
    v_next := v_rec.n;
  end loop;

  if v_next is null then v_next := 1; end if;

  v_candidate := v_prefix || lpad(v_next::text, 3, '0');

  -- Keep the shared sequence counter honest for the legacy trigger.
  -- We just bump it to one past v_next if it is behind; we never
  -- read from it.
  insert into public.school_number_sequences(sequence_key, sequence_year, next_number)
  values ('student', p_year, v_next + 1)
  on conflict (sequence_key, sequence_year) do update
    set next_number = greatest(public.school_number_sequences.next_number, excluded.next_number);

  return v_candidate;
end;
$$;

grant execute on function public.amqm_next_vacant_student_admission_no(integer) to authenticated;

notify pgrst, 'reload schema';
