'use client';
import AdminShell from '@/components/AdminShell';
import {deleteSchoolCalendarEvent,ensureAcademicTerm,loadOperationalTerms,loadSchoolCalendar,saveSchoolCalendarEvent} from '@/lib/live-store';
import {useEffect,useState} from 'react';
export default function CalendarAdmin(){
 const [items,setItems]=useState<any[]>([]),[terms,setTerms]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [academic,setAcademic]=useState({yearName:'2026/27',yearStart:'2026-09-01',yearEnd:'2027-07-31',termNumber:1,termStart:'2026-09-01',termEnd:'2026-12-20'});
 const [form,setForm]=useState({event_type:'evaluation_1',title:'Evaluation 1',starts_on:'',ends_on:'',starts_at:'',ends_at:'',term_id:'',evaluation_number:'1',notes:''});
 const refresh=async()=>{const [c,t]=await Promise.all([loadSchoolCalendar(),loadOperationalTerms()]);setItems(c);setTerms(t)};useEffect(()=>{refresh()},[]);
 async function saveTerm(){setBusy(true);try{await ensureAcademicTerm(academic);setMessage(`${academic.yearName} · Term ${academic.termNumber} is now an operational term and can be used by evaluations.`);await refresh()}catch(e:any){setMessage(e?.message||'Unable to save term')}finally{setBusy(false)}}
 async function add(){setBusy(true);try{await saveSchoolCalendarEvent({...form,term_id:form.term_id||null,evaluation_number:form.event_type.startsWith('evaluation_')?Number(form.evaluation_number):null,starts_at:form.starts_at?new Date(form.starts_at).toISOString():null,ends_at:form.ends_at?new Date(form.ends_at).toISOString():null});setMessage('Calendar event added.');setForm({event_type:'evaluation_1',title:'Evaluation 1',starts_on:'',ends_on:'',starts_at:'',ends_at:'',term_id:'',evaluation_number:'1',notes:''});await refresh()}catch(e:any){setMessage(e?.message||'Unable to save')}finally{setBusy(false)}}
 return <AdminShell title="School Calendar"><div className="space-y-6">
  <section className="rounded-[2rem] bg-gradient-to-br from-slate-950 to-emerald-950 p-6 text-white shadow-xl md:p-8"><div className="text-xs font-bold uppercase tracking-[.22em] text-amber-300">Academic calendar & automation</div><h2 className="mt-2 text-3xl font-black">Set the dates that run the school.</h2><p className="mt-2 max-w-3xl text-sm text-emerald-50/75">Evaluation windows use these exact opening and closing times. The system opens teacher entry automatically and closes it automatically; unfinished evaluations are submitted to Admin when the window closes.</p></section>
  {message&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</div>}
  <section className="card p-5"><div><h2 className="text-xl font-black">Create operational academic term</h2><p className="mt-1 text-sm text-slate-500">These are the real Year/Term records used by evaluations, report cards and progression.</p></div><div className="mt-4 grid gap-3 md:grid-cols-3"><input className="input" placeholder="Academic year e.g. 2026/27" value={academic.yearName} onChange={e=>setAcademic({...academic,yearName:e.target.value})}/><input className="input" type="date" value={academic.yearStart} onChange={e=>setAcademic({...academic,yearStart:e.target.value})}/><input className="input" type="date" value={academic.yearEnd} onChange={e=>setAcademic({...academic,yearEnd:e.target.value})}/><select className="input" value={academic.termNumber} onChange={e=>setAcademic({...academic,termNumber:Number(e.target.value)})}><option value={1}>Term 1</option><option value={2}>Term 2</option><option value={3}>Term 3</option></select><input className="input" type="date" value={academic.termStart} onChange={e=>setAcademic({...academic,termStart:e.target.value})}/><input className="input" type="date" value={academic.termEnd} onChange={e=>setAcademic({...academic,termEnd:e.target.value})}/></div><button className="btn btn-primary mt-4" disabled={busy||!academic.yearName||!academic.termStart||!academic.termEnd} onClick={saveTerm}>Save academic term</button></section>
  <section className="card p-5"><h2 className="text-xl font-black">Schedule a school event or evaluation window</h2><p className="mt-1 text-sm text-slate-500">For evaluations, always provide both date/time fields and link the event to its operational term.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><select className="input" value={form.event_type} onChange={e=>setForm({...form,event_type:e.target.value,evaluation_number:e.target.value.startsWith('evaluation_')?e.target.value.replace('evaluation_',''):''})}><option value="school_opening">School opening</option><option value="school_closing">School closing</option><option value="term_start">Term start</option><option value="term_end">Term end</option><option value="evaluation_1">Evaluation 1</option><option value="evaluation_2">Evaluation 2</option><option value="evaluation_3">Evaluation 3</option><option value="holiday">Holiday</option><option value="screening">Admission screening</option><option value="other">Other</option></select><input className="input" placeholder="Event title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select className="input" value={form.term_id} onChange={e=>setForm({...form,term_id:e.target.value})}><option value="">No operational term</option>{terms.map(t=><option key={t.id} value={t.id}>{t.academic_years?.name} · {t.name}</option>)}</select><input className="input" type="date" value={form.starts_on} onChange={e=>setForm({...form,starts_on:e.target.value})}/><input className="input" type="date" value={form.ends_on} onChange={e=>setForm({...form,ends_on:e.target.value})}/><label className="text-xs font-bold">Opens at<input className="input mt-1" type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label className="text-xs font-bold">Closes at<input className="input mt-1" type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label><textarea className="input md:col-span-2" placeholder="Notes / instructions" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><button disabled={busy||!form.title||!form.starts_on||(form.event_type.startsWith('evaluation_')&&!form.starts_at)} onClick={add} className="btn btn-primary mt-4">Add event</button></section>
  <section className="card overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-black">Configured dates</h2></div><div className="divide-y">{items.map(x=><div key={x.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><b>{x.title}</b><span className="pill bg-emerald-50 text-emerald-700">{x.event_type.replaceAll('_',' ')}</span></div><div className="mt-1 text-xs text-slate-500">{x.starts_at?new Date(x.starts_at).toLocaleString():x.starts_on}{x.ends_at?` → ${new Date(x.ends_at).toLocaleString()}`:(x.ends_on?` → ${x.ends_on}`:'')}{x.notes&&` · ${x.notes}`}</div></div><button className="btn bg-rose-50 text-rose-700" onClick={async()=>{await deleteSchoolCalendarEvent(x.id);await refresh()}}>Delete</button></div>)}{!items.length&&<div className="p-8 text-center text-sm text-slate-500">No calendar events configured.</div>}</div></section>
 </div></AdminShell>
}
