'use client';
import AdminShell from '@/components/AdminShell';
import SectionBadge from '@/components/SectionBadge';
import MemorizationBadge from '@/components/MemorizationBadge';
import { closeTermAndStartNext, createEvaluationCampaign, loadClasses, loadEvaluationCampaigns, loadEvaluations, loadOperationalTerms, reviewEvaluation, loadCurrentAcademicTerm } from '@/lib/live-store';
import { useEffect, useMemo, useState } from 'react';
import { loadCMSSettings } from '@/lib/cms-live-store';

export default function EvaluationsAdmin(){
  const [evals,setEvals]=useState<any[]>([]),[campaigns,setCampaigns]=useState<any[]>([]),[terms,setTerms]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]);
  const [termId,setTermId]=useState(''),[number,setNumber]=useState<1|2|3>(1),[title,setTitle]=useState('Evaluation 1'),[opensAt,setOpensAt]=useState(''),[closesAt,setClosesAt]=useState(''),[selectedClasses,setSelectedClasses]=useState<string[]>([]);
  const [currentTerm,setCurrentTerm]=useState<any>(null); const [campaignFilter,setCampaignFilter]=useState('all'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [expandedClass,setExpandedClass]=useState<string|null>(null),[returnId,setReturnId]=useState<string|null>(null),[returnReason,setReturnReason]=useState('');
  const [detailEvalId,setDetailEvalId]=useState<string|null>(null);
  const [historicalVerified,setHistoricalVerified]=useState(false);
  const refresh=async()=>{const [e,c,t,cl,cur,settings]=await Promise.all([loadEvaluations(),loadEvaluationCampaigns(),loadOperationalTerms(),loadClasses(),loadCurrentAcademicTerm(),loadCMSSettings()]);setEvals(e);setCampaigns(c);setTerms(t);setClasses(cl);setCurrentTerm(cur);setHistoricalVerified(Boolean(settings.amqm_historical_import_verified));if(cur?.term_id&&!termId)setTermId(cur.term_id);};
  useEffect(()=>{refresh()},[]);
  const activeCampaigns=campaigns.filter(c=>c.status==='open'||c.status==='scheduled');
  const pending=evals.filter(e=>e.status==='Pending Approval');
  const returned=evals.filter(e=>e.status==='Returned');
  const approved=evals.filter(e=>e.status==='Approved');
  const currentCampaign=campaigns.find(c=>c.term_id===termId&&c.evaluation_number===number);
  const evalsByClass=useMemo(()=>{
    const termName=terms.find(t=>t.id===termId)?.name;
    const actionable=evals.filter(e=>(e.status==='Pending Approval'||e.status==='Returned')&&(!termName||e.term===termName));
    const map=new Map<string,{className:string,evals:any[]}>();
    for(const ev of actionable){const key=ev.classId||'unassigned';const name=ev.className||'Unassigned';if(!map.has(key))map.set(key,{className:name,evals:[]});map.get(key)!.evals.push(ev);}
    return [...map.entries()].map(([classId,v])=>({classId,...v,evals:v.evals.sort((a,b)=>(b.score||0)-(a.score||0))}));
  },[evals,termId,terms]);
  async function createCampaign(){
    if(!termId||!opensAt||!closesAt||new Date(closesAt)<=new Date(opensAt)||!selectedClasses.length){setMessage('Choose the operational term, evaluation, opening and closing date/time, and at least one class.');return;}
    setBusy(true);setMessage('');try{await createEvaluationCampaign({termId,evaluationNumber:number,title,opensAt,closesAt,classIds:selectedClasses});setMessage(`Evaluation ${number} created for ${selectedClasses.length} class${selectedClasses.length===1?'':'es'}. Teachers will see it automatically at the opening time.`);await refresh();}catch(e:any){setMessage(e?.message||'Unable to create evaluation.')}finally{setBusy(false)}
  }
  async function approve(id:string){setBusy(true);try{await reviewEvaluation(id,'approve','');await refresh();setMessage('Evaluation approved. Official Quran progress and report-card eligibility updated.');}catch(e:any){setMessage(e?.message||'Review failed')}finally{setBusy(false)}}
  async function submitReturn(){if(!returnId)return;setBusy(true);try{await reviewEvaluation(returnId,'return',returnReason.trim()||'Please review and resubmit.');await refresh();setReturnId(null);setReturnReason('');setMessage('Evaluation returned to the teacher.');}catch(e:any){setMessage(e?.message||'Review failed')}finally{setBusy(false)}}
  async function finishTerm(){
    const target=terms.find(t=>t.id===termId); if(!target)return;
    if(!confirm(`Close ${target.name} and start the next configured term? All active students must have Evaluation 1, 2 and 3 approved. Their next term will open from Evaluation 3.`))return;
    setBusy(true);try{const r:any=await closeTermAndStartNext(termId);setMessage(r?.message||'Term closed and next term activated.');await refresh()}catch(e:any){setMessage(e?.message||'Term cannot be closed yet.')}finally{setBusy(false)}
  }
  return <AdminShell title="Quran Evaluations">
    <div className="space-y-6">
      <section className="rounded-[2rem] bg-gradient-to-br from-[#062d2a] via-emerald-900 to-[#9c7420] p-6 text-white shadow-xl md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[11px] font-black uppercase tracking-[.24em] text-amber-300">Assessment control centre</div><h2 className="mt-2 text-3xl font-black md:text-4xl">Run evaluations by class, not by student.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-50/80">The school calendar controls the three evaluation windows. Teachers receive each evaluation automatically, and every approved evaluation becomes the exact opening position for the next one.</p></div><div className="rounded-2xl bg-white/10 p-4 text-sm backdrop-blur"><div className="text-emerald-100/70">Automation</div><div className="mt-1 font-black">Open → Teacher entry → Auto-submit → Review → Approve</div></div></div></section>
      {message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900">{message}</div>}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Pending approval" value={pending.length} tone="amber"/><Kpi label="Approved" value={approved.length} tone="green"/><Kpi label="Returned" value={returned.length} tone="rose"/><Kpi label="Active windows" value={activeCampaigns.length} tone="blue"/></div>

      {!historicalVerified && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div><div className="text-xs font-black uppercase tracking-wider text-amber-700">One-time setup</div><div className="mt-0.5 font-black text-amber-950">Historical Evaluation Import</div><p className="text-xs text-amber-800/70 mt-0.5">Import the school's manual Eval 1–3 records. Historical Eval 3 establishes each student's first live Qur'an opening position.</p></div>
        <a href="/evaluations/historical" className="shrink-0 bg-amber-500 hover:bg-amber-600 text-white text-sm font-bold rounded-xl px-5 py-2.5 transition-colors text-center">Open Import Tool →</a>
      </div>}

      <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-xs font-black uppercase tracking-wider text-emerald-700">Current academic term</div><div className="mt-1 text-lg font-black text-emerald-950">{currentTerm?.academic_year?.name||'Not configured'} · {currentTerm?.term?.name||'Select a term'}</div></div><span className="pill bg-white text-emerald-700">Automatic academic progression</span></div></section><section className="card overflow-hidden"><div className="border-b p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black">Create & send an evaluation</h2><p className="text-sm text-slate-500">There is no student-level entry here. Select classes and the system creates the teacher work queue.</p></div><span className="pill bg-emerald-50 text-emerald-700">Admin only</span></div></div><div className="grid gap-5 p-5 lg:grid-cols-[1fr_1fr]">
        <div className="space-y-3"><label className="block text-xs font-black uppercase tracking-wide text-slate-500">Operational term<select className="input mt-1" value={termId} onChange={e=>{setTermId(e.target.value)}}><option value="">Select term</option>{terms.map(t=><option key={t.id} value={t.id}>{t.academic_years?.name||'Academic year'} · {t.name} · {t.starts_on} → {t.ends_on}</option>)}</select></label><label className="block text-xs font-black uppercase tracking-wide text-slate-500">Evaluation<select className="input mt-1" value={number} onChange={e=>{setNumber(Number(e.target.value) as 1|2|3);setTitle(`Evaluation ${e.target.value}`)}}><option value="1">Evaluation 1</option><option value="2">Evaluation 2</option><option value="3">Evaluation 3</option></select></label><label className="block text-xs font-black uppercase tracking-wide text-slate-500">Title<input className="input mt-1" value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-black uppercase tracking-wide text-slate-500">Opens<input className="input mt-1" type="datetime-local" value={opensAt} onChange={e=>setOpensAt(e.target.value)}/></label><label className="block text-xs font-black uppercase tracking-wide text-slate-500">Closes<input className="input mt-1" type="datetime-local" min={opensAt||undefined} value={closesAt} onChange={e=>setClosesAt(e.target.value)}/></label></div></div>
        <div><div className="text-xs font-black uppercase tracking-wide text-slate-500">Send to classes</div><div className="mt-1 rounded-2xl border bg-slate-50 p-3"><label className="flex items-center gap-3 rounded-xl bg-white p-3 font-bold"><input type="checkbox" checked={selectedClasses.length===classes.filter(c=>c.active).length&&classes.length>0} onChange={e=>setSelectedClasses(e.target.checked?classes.filter(c=>c.active).map(c=>c.id):[])}/><span>All active classes</span></label><div className="mt-2 grid gap-2 sm:grid-cols-2">{classes.filter(c=>c.active).map(c=><label key={c.id} className={`flex items-center justify-between rounded-xl border p-3 ${selectedClasses.includes(c.id)?'border-emerald-500 bg-emerald-50':'bg-white'}`}><span className="min-w-0"><input type="checkbox" className="mr-2" checked={selectedClasses.includes(c.id)} onChange={e=>setSelectedClasses(v=>e.target.checked?[...v,c.id]:v.filter(x=>x!==c.id))}/><b>{c.name}</b><span className="ml-1 text-xs text-slate-400">{c.code}</span></span><span className="text-xs text-slate-500">{c.teachers?.length||0} teacher(s)</span></label>)}</div></div><div className="mt-4 rounded-2xl bg-emerald-950 p-4 text-sm text-emerald-50"><b className="text-white">What happens next?</b><ul className="mt-2 space-y-1 text-xs leading-5 text-emerald-100/80"><li>• Draft evaluation records are created for students in the selected classes.</li><li>• They automatically open to assigned teachers at the calendar start time.</li><li>• At the closing time, unfinished drafts are auto-submitted for Admin review.</li><li>• Submitted records disappear from the teacher until Admin returns one.</li></ul></div></div>
      </div><div className="flex flex-wrap justify-end gap-2 border-t bg-slate-50 p-4"><button className="btn bg-white" onClick={()=>{setTermId('');setOpensAt('');setClosesAt('');setSelectedClasses([])}}>Reset</button><button className="btn btn-primary" disabled={busy||!termId||!opensAt||!closesAt||new Date(closesAt)<=new Date(opensAt)||!selectedClasses.length||!!currentCampaign} onClick={createCampaign}>{currentCampaign?'Already created':'Create & send evaluation'}</button></div></section>

      <section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-black">Evaluation campaigns</h2><p className="text-sm text-slate-500">Each campaign has its own opening and closing window and targets a specific set of classes.</p></div><div className="flex flex-wrap gap-2">{['all','scheduled','open','closed','completed'].map(x=><button key={x} className={`btn ${campaignFilter===x?'bg-slate-900 text-white':'bg-slate-100'}`} onClick={()=>setCampaignFilter(x)}>{x}</button>)}</div></div><div className="divide-y">{campaigns.filter(c=>campaignFilter==='all'||c.status===campaignFilter).map(c=><div key={c.id} className="p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{c.title}</h3><span className={`pill ${c.status==='open'?'bg-emerald-50 text-emerald-700':c.status==='scheduled'?'bg-blue-50 text-blue-700':'bg-slate-100'}`}>{c.status}</span></div><div className="mt-1 text-xs text-slate-500">{c.terms?.name||'Term'} · Evaluation {c.evaluation_number} · {new Date(c.opens_at).toLocaleString()} → {new Date(c.closes_at).toLocaleString()}</div></div><div className="text-sm font-bold">{(c.evaluation_campaign_classes||[]).length} classes</div></div><div className="mt-3 flex flex-wrap gap-2">{(c.evaluation_campaign_classes||[]).map((x:any)=><span className="pill bg-slate-50" key={x.class_id}>{x.classes?.name||'Class'}</span>)}</div></div>)}{!campaigns.length&&<div className="p-10 text-center text-sm text-slate-500">No evaluation campaigns yet.</div>}</div></section>

      <section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-black">Pending review — by class</h2><p className="text-sm text-slate-500">Evaluations submitted by teachers, grouped by class. Open a class to approve or return individual evaluations.</p></div><button className="btn bg-emerald-50 text-emerald-800" onClick={finishTerm} disabled={busy||!termId}>Close Term &amp; Start Next Term</button></div>
        {evalsByClass.length===0?<div className="p-10 text-center text-sm text-slate-500">No evaluations awaiting review.</div>:evalsByClass.map(({classId,className,evals:classEvals})=>{const open=expandedClass===classId;const pendingCount=classEvals.filter(e=>e.status==='Pending Approval').length;const returnedCount=classEvals.filter(e=>e.status==='Returned').length;return <div key={classId} className="border-t"><button className="flex w-full items-center justify-between p-5 text-left hover:bg-slate-50" onClick={()=>setExpandedClass(open?null:classId)}><div><div className="font-black">{className}</div><div className="mt-1 flex gap-3 text-xs"><span className="text-amber-700">{pendingCount} pending</span>{returnedCount>0&&<span className="text-rose-700">{returnedCount} returned</span>}</div></div><span className="text-slate-400">{open?'▲':'▼'}</span></button>
          {open&&<div className="divide-y border-t bg-slate-50">{classEvals.map((ev,idx)=><div key={ev.id} className="p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-200 font-black text-slate-500 text-sm">#{idx+1}</div><div className="flex items-center gap-3"><div className="h-10 w-10 shrink-0 overflow-hidden rounded-xl bg-slate-200">{ev.photoUrl?<img src={ev.photoUrl} className="h-full w-full object-cover" alt=""/>:<div className="grid h-full place-items-center font-black text-slate-400">{ev.student?.charAt(0)}</div>}</div><div><div className="flex flex-wrap items-center gap-2"><b>{ev.student}</b>{ev.score>0&&<span className="font-black text-emerald-700">{ev.score}%</span>}<StatusBadge status={ev.status}/></div><div className="text-xs text-slate-500 mt-0.5">{ev.admissionNo} · Eval {ev.number}</div><div className="mt-1 flex flex-wrap gap-1"><MemorizationBadge direction={ev.memorizationDirection}/><SectionBadge section={ev.studentSection}/></div></div></div></div>
            <div className="flex flex-col gap-2">
              <button className="btn bg-slate-100 text-xs" onClick={()=>setDetailEvalId(detailEvalId===ev.id?null:ev.id)}>{detailEvalId===ev.id?'Hide details':'View details'}</button>
              {ev.status==='Pending Approval'&&returnId!==ev.id&&<div className="flex gap-2"><button className="btn btn-green" disabled={busy} onClick={()=>approve(ev.id)}>Approve</button><button className="btn bg-rose-50 text-rose-700" disabled={busy} onClick={()=>{setReturnId(ev.id);setReturnReason('');}}>Return</button></div>}
              {returnId===ev.id&&<div className="flex flex-col gap-2"><textarea className="input min-h-[72px] resize-none text-sm" placeholder="Reason for returning (shown to teacher)" value={returnReason} onChange={e=>setReturnReason(e.target.value)}/><div className="flex gap-2"><button className="btn btn-primary text-sm" disabled={busy} onClick={submitReturn}>Submit return</button><button className="btn bg-white text-sm" onClick={()=>setReturnId(null)}>Cancel</button></div></div>}
              {ev.status==='Returned'&&<span className="text-xs font-bold text-rose-700">Awaiting teacher correction</span>}
            </div>
          </div>
          {detailEvalId===ev.id&&<div className="mt-3 rounded-2xl border bg-white p-4">
            <div className="mb-3 text-xs font-black uppercase tracking-wide text-slate-500">Evaluation details</div>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
              <InfoCell k="Memorized ayahs" v={String(ev.memorizedAyahs||0)}/>
              <InfoCell k="Pages covered" v={String(ev.memorizedPages||0)}/>
              <InfoCell k="Hizb covered" v={String(ev.memorizedHizbs||0)}/>
              <InfoCell k="Final score" v={ev.score>0?`${ev.score}%`:'—'}/>
            </div>
            <div className="mt-3 grid grid-cols-5 gap-2">
              {[['Memorization',ev.memorization],['Accuracy',ev.accuracy],['Fluency',ev.fluency],['Tajweed',ev.tajweed],['Retention',ev.retention]].map(([lbl,val])=><div key={String(lbl)} className="rounded-xl bg-slate-50 p-2 text-center"><div className="text-[10px] font-bold uppercase text-slate-400">{lbl}</div><div className="mt-1 text-lg font-black text-emerald-800">{val||'—'}/5</div></div>)}
            </div>
            {ev.grade&&<div className="mt-3 rounded-xl bg-emerald-50 px-3 py-2 text-sm font-black text-emerald-800">{ev.grade}</div>}
            {ev.comment&&<div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-700"><span className="font-bold">Teacher comment: </span>{ev.comment}</div>}
          </div>}
          </div>)}</div>}</div>;})}
      </section>
    </div>
  </AdminShell>
}
function Kpi({label,value,tone}:{label:string,value:number,tone:string}){const bg=tone==='green'?'bg-emerald-50 text-emerald-900':tone==='amber'?'bg-amber-50 text-amber-900':tone==='rose'?'bg-rose-50 text-rose-900':tone==='blue'?'bg-blue-50 text-blue-900':'bg-slate-50 text-slate-900';return <div className={`rounded-2xl p-5 ${bg}`}><div className="text-xs font-bold uppercase tracking-wide opacity-70">{label}</div><div className="mt-2 text-3xl font-black">{value}</div></div>}
function StatusBadge({status}:{status:string}){const cls=status==='Approved'?'bg-emerald-50 text-emerald-700':status==='Pending Approval'?'bg-amber-50 text-amber-700':status==='Returned'?'bg-rose-50 text-rose-700':status==='Draft'?'bg-blue-50 text-blue-700':'bg-slate-100 text-slate-500';return <span className={`pill ${cls}`}>{status}</span>}
function InfoCell({k,v}:{k:string;v:string}){return <div className="rounded-xl bg-slate-50 p-2"><div className="text-[10px] font-bold uppercase text-slate-400">{k}</div><div className="mt-0.5 text-sm font-black">{v}</div></div>}
