'use client';
import AdminShell from '@/components/AdminShell';
import { assignTeacherToClass,createClass,createStaffAccount,loadAcademicYears,loadClasses,loadStaffProfiles,removeTeacherFromClass,updateStaffProfile,uploadProfileImage,type LiveClass } from '@/lib/live-store';
import { useEffect,useMemo,useState } from 'react';

type Teacher={id:string;name:string;staff_id?:string;avatar_url?:string|null;phone?:string|null;job_title?:string|null;employment_status?:string};
type AcademicYear={id:string;name:string;is_current:boolean};
export default function ClassesPage(){
 const [classes,setClasses]=useState<LiveClass[]>([]),[teachers,setTeachers]=useState<Teacher[]>([]),[years,setYears]=useState<AcademicYear[]>([]),[showCreate,setShowCreate]=useState(false),[showTeacher,setShowTeacher]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [form,setForm]=useState({name:'',code:'',academicYearId:'',programYear:'',capacity:''});
 const [teacherForm,setTeacherForm]=useState({fullName:'',email:'',password:'',phone:'',jobTitle:'Qur’an Teacher',department:'Qur’an Memorization',joinedOn:''});
 const [selectedTeacher,setSelectedTeacher]=useState<Record<string,string>>({});
 const refresh=async()=>{const [c,t,y]=await Promise.all([loadClasses(),loadStaffProfiles(),loadAcademicYears()]);setClasses(c);setTeachers(t.filter((x:any)=>x.role==='teacher')) ;setYears(y)};
 useEffect(()=>{refresh()},[]);
 async function submitClass(e:React.FormEvent){e.preventDefault();setBusy(true);try{await createClass({name:form.name,code:form.code,academicYearId:form.academicYearId||null,programYear:(form.programYear||null) as any,capacity:form.capacity?Number(form.capacity):null});setForm({name:'',code:'',academicYearId:'',programYear:'',capacity:''});setShowCreate(false);await refresh();setMessage('Class created successfully.')}catch(err:any){setMessage(err?.message??'Unable to create class.')}finally{setBusy(false)}}
 async function createTeacher(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await createStaffAccount({...teacherForm,role:'teacher'});setShowTeacher(false);setTeacherForm({fullName:'',email:'',password:'',phone:'',jobTitle:'Qur’an Teacher',department:'Qur’an Memorization',joinedOn:''});await refresh();setMessage(`Teacher account created. Staff ID: ${r?.staff_id||'assigned automatically'}.`)}catch(err:any){setMessage(err?.message??'Unable to create teacher.')}finally{setBusy(false)}}
 async function addTeacher(classId:string){const teacherId=selectedTeacher[classId];if(!teacherId)return;setBusy(true);try{await assignTeacherToClass(classId,teacherId,false);await refresh();setSelectedTeacher(v=>({...v,[classId]:''}));setMessage('Teacher assigned to class.')}catch(err:any){setMessage(err?.message??'Unable to assign teacher.')}finally{setBusy(false)}}
 async function removeTeacher(classId:string,teacherId:string){setBusy(true);try{await removeTeacherFromClass(classId,teacherId);await refresh();setMessage('Teacher assignment removed.')}catch(err:any){setMessage(err?.message??'Unable to remove assignment.')}finally{setBusy(false)}}
 function printTeacher(t:Teacher){const w=window.open('','_blank','width=900,height=650');if(!w)return;w.document.write(`<html><head><title>AMQM Teacher ID - ${t.full_name||t.name}</title><style>body{font-family:Arial;padding:40px;background:#eef4f1}.card{width:420px;border-radius:24px;background:#062d2a;color:#fff;padding:28px;margin:auto;box-shadow:0 20px 60px #0002}.gold{color:#e5b84b}.photo{width:92px;height:92px;border-radius:20px;object-fit:cover;background:#fff2}.id{font-size:12px;letter-spacing:2px;color:#d9efe8}.name{font-size:28px;font-weight:800;margin-top:12px}.meta{margin-top:6px;color:#d9efe8}.line{height:1px;background:#ffffff22;margin:22px 0}@media print{body{background:white}.card{box-shadow:none}}</style></head><body><div class="card">${t.avatar_url?`<img class="photo" src="${t.avatar_url}"/>`:`<div class="photo"></div>`}<div class="id gold">ALIYU AND MAIMUNA CENTER FOR QUR'ANIC MEMORIZATION</div><div class="name">${t.name}</div><div class="meta">${t.job_title||'Qur’an Teacher'}</div><div class="line"></div><div class="id">STAFF ID</div><div style="font-size:20px;font-weight:800;margin-top:5px">${t.staff_id||'AMQM-STAFF'}</div><div class="meta">${t.phone||''}</div></div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
 return <AdminShell title="Classes & Teachers"><div className="space-y-6">
  <section className="rounded-[2rem] bg-gradient-to-br from-[#062d2a] via-emerald-900 to-[#a17821] p-6 text-white shadow-xl md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[11px] font-black uppercase tracking-[.24em] text-amber-300">People & classroom control</div><h2 className="mt-2 text-3xl font-black">Build the right teaching team.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-50/80">Create teachers, give them professional profiles, assign them to classes and print school ID cards. Class assignments automatically determine their student work queues.</p></div><div className="flex flex-wrap gap-2"><button className="btn bg-white text-emerald-950" onClick={()=>setShowTeacher(true)}>+ Create teacher</button><button className="btn bg-white/10 text-white" onClick={()=>setShowCreate(true)}>+ Create class</button></div></div></section>
  {message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900">{message}</div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Teachers" value={teachers.length}/><Kpi label="Active classes" value={classes.filter(c=>c.active).length}/><Kpi label="Assigned classes" value={classes.filter(c=>c.teachers.length).length}/><Kpi label="Unassigned classes" value={classes.filter(c=>!c.teachers.length).length}/></div>
  <section className="card overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-black">Teachers</h2><p className="text-sm text-slate-500">Teacher accounts are created here; teacher portal permissions remain restricted.</p></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{teachers.map(t=><article key={t.id} className="rounded-2xl border p-4"><div className="flex items-center gap-3"><div className="h-14 w-14 overflow-hidden rounded-2xl bg-slate-100">{t.avatar_url?<img src={t.avatar_url} className="h-full w-full object-cover" alt=""/>:<div className="grid h-full place-items-center font-black text-slate-400">{t.name.charAt(0)}</div>}</div><div className="min-w-0"><div className="font-black">{t.name}</div><div className="text-xs text-emerald-700">{t.staff_id||'Staff ID pending'}</div><div className="text-xs text-slate-500">{t.job_title||'Teacher'}</div></div></div><div className="mt-4 flex gap-2"><label className="btn flex-1 bg-slate-100 cursor-pointer">Upload photo<input hidden type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{setBusy(true);const url=await uploadProfileImage(f,'staff');await updateStaffProfile(t.id,{avatar_url:url});await refresh();setMessage('Teacher photo updated.')}catch(err:any){setMessage(err?.message||'Upload failed')}finally{setBusy(false)}}}/></label><button className="btn bg-emerald-50 text-emerald-800" onClick={()=>printTeacher(t)}>Print ID</button></div></article>)}{!teachers.length&&<div className="p-8 text-center text-sm text-slate-500 md:col-span-2 xl:col-span-3">No teachers yet. Create the first teacher above.</div>}</div></section>
  <section><div className="mb-3"><h2 className="text-xl font-black">Classes & assignments</h2><p className="text-sm text-slate-500">Assign one or more teachers. The primary teacher is used for the evaluation work queue when an evaluation is sent.</p></div><div className="grid gap-4 lg:grid-cols-2">{classes.map(c=><div className="card p-5" key={c.id}><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-wide text-slate-400">{c.code}</div><h2 className="text-xl font-black">{c.name}</h2><div className="mt-1 text-sm text-slate-500">{c.academicYearName??'No academic year'} · {c.programYear??'Programme year not set'}</div></div><span className={`pill ${c.active?'bg-emerald-50 text-emerald-700':'bg-slate-100'}`}>{c.active?'Active':'Inactive'}</span></div><div className="mt-4 rounded-2xl bg-slate-50 p-4"><div className="text-xs font-bold uppercase text-slate-400">Assigned teachers</div><div className="mt-2 space-y-2">{c.teachers.length?c.teachers.map(t=><div className="flex items-center justify-between rounded-xl bg-white p-3" key={t.id}><span className="text-sm font-semibold">{t.name}{t.primary?' · Primary':''}</span><button className="text-xs font-bold text-rose-600" onClick={()=>removeTeacher(c.id,t.id)} disabled={busy}>Remove</button></div>):<div className="text-sm text-slate-500">No teachers assigned yet.</div>}</div><div className="mt-3 flex gap-2"><select className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm" value={selectedTeacher[c.id]??''} onChange={e=>setSelectedTeacher(v=>({...v,[c.id]:e.target.value}))}><option value="">Select teacher...</option>{teachers.filter(t=>!c.teachers.some(ct=>ct.id===t.id)).map(t=><option value={t.id} key={t.id}>{t.name}{t.staff_id?` · ${t.staff_id}`:''}</option>)}</select><button className="btn bg-slate-900 text-white" onClick={()=>addTeacher(c.id)} disabled={busy||!selectedTeacher[c.id]}>Assign</button></div></div><div className="mt-3 text-xs text-slate-500">Capacity: {c.capacity??'Not set'} · Day + Boarding students can share this class.</div></div>)}</div>{!classes.length&&<div className="card p-8 text-center text-sm text-slate-500">No classes have been created yet.</div>}</section>
  {showCreate&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4"><div className="mx-auto mt-8 w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Create class</h2><p className="text-sm text-slate-500">Classes are shared across Day and Boarding.</p></div><button className="btn bg-slate-100" onClick={()=>setShowCreate(false)}>Close</button></div><form onSubmit={submitClass} className="mt-5 grid gap-3 md:grid-cols-2"><input required className="input" placeholder="Class name e.g. Year 1 A" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required className="input uppercase" placeholder="Class code e.g. Y1-A" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><select className="input" value={form.academicYearId} onChange={e=>setForm({...form,academicYearId:e.target.value})}><option value="">No academic year</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.is_current?' · Current':''}</option>)}</select><select className="input" value={form.programYear} onChange={e=>setForm({...form,programYear:e.target.value})}><option value="">Programme year</option><option value="year_1">Year 1</option><option value="year_2">Year 2</option></select><input min="1" type="number" className="input" placeholder="Capacity (optional)" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/><div className="md:col-span-2 flex justify-end gap-2"><button type="button" className="btn bg-slate-100" onClick={()=>setShowCreate(false)}>Cancel</button><button disabled={busy} className="btn btn-primary">{busy?'Creating…':'Create class'}</button></div></form></div></div>}
  {showTeacher&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4"><div className="mx-auto mt-8 w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Create teacher</h2><p className="text-sm text-slate-500">The account receives the restricted Teacher Workspace only.</p></div><button className="btn bg-slate-100" onClick={()=>setShowTeacher(false)}>Close</button></div><form onSubmit={createTeacher} className="mt-5 grid gap-3 md:grid-cols-2"><input required className="input" placeholder="Full name" value={teacherForm.fullName} onChange={e=>setTeacherForm({...teacherForm,fullName:e.target.value})}/><input required type="email" className="input" placeholder="Email" value={teacherForm.email} onChange={e=>setTeacherForm({...teacherForm,email:e.target.value})}/><input required minLength={8} type="password" className="input" placeholder="Temporary password (8+ characters)" value={teacherForm.password} onChange={e=>setTeacherForm({...teacherForm,password:e.target.value})}/><input className="input" placeholder="Phone" value={teacherForm.phone} onChange={e=>setTeacherForm({...teacherForm,phone:e.target.value})}/><input className="input" placeholder="Job title" value={teacherForm.jobTitle} onChange={e=>setTeacherForm({...teacherForm,jobTitle:e.target.value})}/><input className="input" placeholder="Department" value={teacherForm.department} onChange={e=>setTeacherForm({...teacherForm,department:e.target.value})}/><input type="date" className="input" value={teacherForm.joinedOn} onChange={e=>setTeacherForm({...teacherForm,joinedOn:e.target.value})}/><div className="md:col-span-2 flex justify-end gap-2"><button type="button" className="btn bg-slate-100" onClick={()=>setShowTeacher(false)}>Cancel</button><button disabled={busy} className="btn btn-primary">{busy?'Creating…':'Create teacher'}</button></div></form></div></div>}
 </div></AdminShell>
}
function Kpi({label,value}:{label:string,value:number}){return <div className="card p-5"><div className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-2 text-3xl font-black">{value}</div></div>}
