'use client';
import AdminShell from '@/components/AdminShell';
import Link from 'next/link';
import { assignTeacherToClass,createClass,loadAcademicYears,loadClasses,loadStaffProfiles,removeTeacherFromClass,type LiveClass } from '@/lib/live-store';
import { useEffect,useMemo,useState } from 'react';

type Teacher={id:string;name:string;full_name?:string;staff_id?:string;avatar_url?:string|null;phone?:string|null;job_title?:string|null;department?:string|null;employment_status?:string;id_expires_on?:string|null};
type AcademicYear={id:string;name:string;is_current:boolean};
export default function ClassesPage(){
 const [classes,setClasses]=useState<LiveClass[]>([]),[teachers,setTeachers]=useState<Teacher[]>([]),[years,setYears]=useState<AcademicYear[]>([]),[showCreate,setShowCreate]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(‘’);
 const [form,setForm]=useState({name:’’,code:’’,academicYearId:’’,programYear:’’,capacity:’’});
 const [selectedTeacher,setSelectedTeacher]=useState<Record<string,string>>({});
 const refresh=async()=>{const [c,t,y]=await Promise.all([loadClasses(),loadStaffProfiles(),loadAcademicYears()]);setClasses(c);setTeachers(t.filter((x:any)=>x.role===’teacher’).map((x:any)=>({...x,name:x.full_name})));setYears(y)};
 useEffect(()=>{refresh()},[]);
 async function submitClass(e:React.FormEvent){e.preventDefault();setBusy(true);try{await createClass({name:form.name,code:form.code,academicYearId:form.academicYearId||null,programYear:(form.programYear||null) as any,capacity:form.capacity?Number(form.capacity):null});setForm({name:’’,code:’’,academicYearId:’’,programYear:’’,capacity:’’});setShowCreate(false);await refresh();setMessage(‘Class created successfully.’)}catch(err:any){setMessage(err?.message??’Unable to create class.’)}finally{setBusy(false)}}
 async function addTeacher(classId:string){const teacherId=selectedTeacher[classId];if(!teacherId)return;setBusy(true);try{await assignTeacherToClass(classId,teacherId,false);await refresh();setSelectedTeacher(v=>({...v,[classId]:’’}));setMessage(‘Teacher assigned to class.’)}catch(err:any){setMessage(err?.message??’Unable to assign teacher.’)}finally{setBusy(false)}}
 async function removeTeacher(classId:string,teacherId:string){setBusy(true);try{await removeTeacherFromClass(classId,teacherId);await refresh();setMessage(‘Teacher assignment removed.’)}catch(err:any){setMessage(err?.message??’Unable to remove assignment.’)}finally{setBusy(false)}}
 return <AdminShell title="Classes & Teachers"><div className="space-y-6">
  <section className="rounded-[2rem] bg-gradient-to-br from-[#062d2a] via-emerald-900 to-[#a17821] p-6 text-white shadow-xl md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[11px] font-black uppercase tracking-[.24em] text-amber-300">People & classroom control</div><h2 className="mt-2 text-3xl font-black">Build the right teaching team.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-50/80">Create teachers, give them professional profiles, assign them to classes and print school ID cards. Class assignments automatically determine their student work queues.</p></div><div className="flex flex-wrap gap-2"><Link href="/staff" className="btn bg-white/10 text-white">Manage staff →</Link><button className="btn bg-white text-emerald-950" onClick={()=>setShowCreate(true)}>+ Create class</button></div></div></section>
  {message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900">{message}</div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Teachers" value={teachers.length}/><Kpi label="Active classes" value={classes.filter(c=>c.active).length}/><Kpi label="Assigned classes" value={classes.filter(c=>c.teachers.length).length}/><Kpi label="Unassigned classes" value={classes.filter(c=>!c.teachers.length).length}/></div>
  <div className="flex items-center justify-between rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div><div className="text-sm font-bold text-emerald-900">Teachers — {teachers.length} on record</div><div className="text-xs text-emerald-700 mt-0.5">Create, edit profiles, upload photos and manage website visibility from Staff.</div></div><Link href="/staff" className="btn bg-emerald-700 text-white text-sm">Open Staff →</Link></div>
  <section><div className="mb-3"><h2 className="text-xl font-black">Classes & assignments</h2><p className="text-sm text-slate-500">Assign one or more teachers. The primary teacher is used for the evaluation work queue when an evaluation is sent.</p></div><div className="grid gap-4 lg:grid-cols-2">{classes.map(c=><div className="card p-5" key={c.id}><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-wide text-slate-400">{c.code}</div><h2 className="text-xl font-black">{c.name}</h2><div className="mt-1 text-sm text-slate-500">{c.academicYearName??'No academic year'} · {c.programYear??'Programme year not set'}</div></div><span className={`pill ${c.active?'bg-emerald-50 text-emerald-700':'bg-slate-100'}`}>{c.active?'Active':'Inactive'}</span></div><div className="mt-4 rounded-2xl bg-slate-50 p-4"><div className="text-xs font-bold uppercase text-slate-400">Assigned teachers</div><div className="mt-2 space-y-2">{c.teachers.length?c.teachers.map(t=><div className="flex items-center justify-between rounded-xl bg-white p-3" key={t.id}><span className="text-sm font-semibold">{t.name}{t.primary?' · Primary':''}</span><button className="text-xs font-bold text-rose-600" onClick={()=>removeTeacher(c.id,t.id)} disabled={busy}>Remove</button></div>):<div className="text-sm text-slate-500">No teachers assigned yet.</div>}</div><div className="mt-3 flex gap-2"><select className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm" value={selectedTeacher[c.id]??''} onChange={e=>setSelectedTeacher(v=>({...v,[c.id]:e.target.value}))}><option value="">Select teacher...</option>{teachers.filter(t=>!c.teachers.some(ct=>ct.id===t.id)).map(t=><option value={t.id} key={t.id}>{t.name}{t.staff_id?` · ${t.staff_id}`:''}</option>)}</select><button className="btn bg-slate-900 text-white" onClick={()=>addTeacher(c.id)} disabled={busy||!selectedTeacher[c.id]}>Assign</button></div></div><div className="mt-3 text-xs text-slate-500">Capacity: {c.capacity??'Not set'} · Day + Boarding students can share this class.</div></div>)}</div>{!classes.length&&<div className="card p-8 text-center text-sm text-slate-500">No classes have been created yet.</div>}</section>
  {showCreate&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4"><div className="mx-auto mt-8 w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Create class</h2><p className="text-sm text-slate-500">Classes are shared across Day and Boarding.</p></div><button className="btn bg-slate-100" onClick={()=>setShowCreate(false)}>Close</button></div><form onSubmit={submitClass} className="mt-5 grid gap-3 md:grid-cols-2"><input required className="input" placeholder="Class name e.g. Year 1 A" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required className="input uppercase" placeholder="Class code e.g. Y1-A" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><select className="input" value={form.academicYearId} onChange={e=>setForm({...form,academicYearId:e.target.value})}><option value="">No academic year</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.is_current?' · Current':''}</option>)}</select><select className="input" value={form.programYear} onChange={e=>setForm({...form,programYear:e.target.value})}><option value="">Programme year</option><option value="year_1">Year 1</option><option value="year_2">Year 2</option></select><input min="1" type="number" className="input" placeholder="Capacity (optional)" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/><div className="md:col-span-2 flex justify-end gap-2"><button type="button" className="btn bg-slate-100" onClick={()=>setShowCreate(false)}>Cancel</button><button disabled={busy} className="btn btn-primary">{busy?'Creating…':'Create class'}</button></div></form></div></div>}
 </div></AdminShell>
}
function Kpi({label,value}:{label:string,value:number}){return <div className="card p-5"><div className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-2 text-3xl font-black">{value}</div></div>}
